[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
PYTHON = "python3"
npm_config_python = "python3"
SHARP_IGNORE_GLOBAL_LIBVIPS = "0"

[phases.setup]
# Use Node 22 and install Bun (project uses Bun for scripts) and build deps
nixPkgs = ["nodejs_22", "python3", "gcc", "gnumake", "pkg-config", "git", "vips", "curl", "unzip"]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "mv /root/.bun/bin/bun /usr/local/bin/bun"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "/usr/local/bin/bun install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "/usr/local/bin/bun run build"
]

[start]
cmd = "/usr/local/bin/bun run start"

