# documentation: https://github.com/hyperfy-xyz/hyperfy
# slogan: Host virtual worlds in the browser - an open-source metaverse platform
# tags: metaverse,3d,virtual-worlds,gaming,web3
# logo: svgs/hyperfy.svg
# port: 3000

services:
  hyperfy:
    image: 'ghcr.io/hyperfy-xyz/hyperfy:dev'
    environment:
      - SERVICE_FQDN_HYPERFY_3000
      - PORT=3000
      - 'WORLD=${WORLD:-world}'
      - 'JWT_SECRET=${SERVICE_PASSWORD_JWT}'
      - 'ADMIN_CODE=${SERVICE_PASSWORD_ADMIN}'
      - 'FOLDER=${FOLDER:-play}'
      - 'SAVE_INTERVAL=${SAVE_INTERVAL:-60}'
      - 'PUBLIC_PLAYER_COLLISION=${PUBLIC_PLAYER_COLLISION:-true}'
      - 'PUBLIC_MAX_UPLOAD_SIZE=${PUBLIC_MAX_UPLOAD_SIZE:-100}'
      - 'PUBLIC_WS_URL=${SERVICE_FQDN_HYPERFY}/ws'
      - 'PUBLIC_API_URL=${SERVICE_FQDN_HYPERFY}/api'
      - 'PUBLIC_ASSETS_URL=${SERVICE_FQDN_HYPERFY}/assets'
      - 'LIVEKIT_WS_URL=${LIVEKIT_WS_URL}'
      - 'LIVEKIT_API_KEY=${LIVEKIT_API_KEY}'
      - 'LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}'
    volumes:
      - hyperfy-worlds:/app/world
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -f http://127.0.0.1:3000 || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  hyperfy-worlds: 