import "server-only";
import { cache } from "react";
import { unstable_cache } from "next/cache";
import {
  aggregate,
  createDirectus,
  readItems,
  rest,
} from "@directus/sdk";

// Published museum content (collections, NFTs, rooms) changes rarely, so reads
// are cached for an hour via the Next Data Cache (unstable_cache). This works
// even on the dynamic, searchParams-driven gallery route, where the route
// itself can't be statically rendered — the underlying Directus reads still
// come from cache. `react.cache` adds per-request dedup on top (e.g.
// getCollection is called by both generateMetadata and the page in one render).
const REVALIDATE_SECONDS = 3600;
const CACHE_TAG = "museum-content";

// Public, read-only Directus client for published museum content (collections,
// NFTs, rooms). No auth needed — these read policies are public on the CMS.
// Server-only: keeps the CMS URL and all fetching on the server (galleries
// render as Server Components).

export interface Collection {
  id: number;
  name: string;
  title?: string | null;
  description?: string | null;
  essay?: string | null;
  slug: string;
  status?: string;
  sort?: number | null;
  parent_collection?: number | null;
  child_collections?: { id: number; name: string; slug: string }[];
}

export interface Nft {
  id: number;
  name?: string | null;
  artist_name?: string | null;
  collection?: string | null;
  media_info?: unknown;
  display_media_info?: unknown;
  display_animation_info?: unknown;
  response_opensea?: unknown;
}

export interface Room {
  id: number;
  title?: string | null;
  architect?: string | null;
  description?: string | null;
  series?: string | null;
  slots?: number | null;
  image?: string | null;
  /** Untouched high-quality GLB — the /rooms/[id] HQ viewer. */
  model?: string | null;
  /**
   * Optimized GLB (draco + webp) with embedded Slot_NNN placeholders — the
   * exhibition builder variant. Generated by apps/migration/embed-room-slots.ts.
   */
  model_optimized?: string | null;
  token_id?: string | null;
}

interface Schema {
  collections: Collection[];
  nfts: Nft[];
  rooms: Room[];
}

function getDirectusUrl(): string {
  return process.env.DIRECTUS_URL || "https://api.moca.qwellco.de";
}

function client() {
  return createDirectus<Schema>(getDirectusUrl()).with(rest());
}

/** On-the-fly image transform options for the Directus assets endpoint. */
export interface AssetTransform {
  width?: number;
  height?: number;
  quality?: number;
  fit?: "cover" | "contain" | "inside" | "outside";
  format?: "webp" | "jpg" | "png" | "auto";
}

/**
 * Asset URL for a Directus file id (rooms images/models). Pass `transform` to
 * have Directus generate (and cache) a resized/re-encoded variant on demand —
 * the source room images are multi-megabyte JPEGs, so requesting a sized WebP
 * thumbnail cuts payloads ~100x. Transforms are cached at the origin/CDN, so
 * the first request warms every later one. Models (.glb/.gltf) take no transform.
 */
export function assetUrl(fileId?: string | null, transform?: AssetTransform): string {
  if (!fileId) return "";
  const base = `${getDirectusUrl()}/assets/${fileId}`;
  if (!transform) return base;
  const params = new URLSearchParams();
  if (transform.width) params.set("width", String(transform.width));
  if (transform.height) params.set("height", String(transform.height));
  if (transform.quality) params.set("quality", String(transform.quality));
  if (transform.fit) params.set("fit", transform.fit);
  if (transform.format) params.set("format", transform.format);
  const qs = params.toString();
  return qs ? `${base}?${qs}` : base;
}

export const DEFAULT_COLLECTION_SLUG = "the-genesis-collection";
export const NFTS_PER_PAGE = 24;

/** Top-level (parent) published collections — for galleries index + nav. */
export const listTopCollections = unstable_cache(
  async (): Promise<Collection[]> => {
    const rows = await client().request(
      readItems("collections", {
        fields: [
          "id",
          "name",
          "title",
          "description",
          "slug",
          "sort",
          { child_collections: [ "id", "name", "slug" ] },
        ],
        filter: {
          _and: [
            { status: { _eq: "published" } },
            { parent_collection: { _null: true } },
          ],
        },
        sort: [ "sort", "name" ],
        limit: -1,
      }),
    );
    return rows as unknown as Collection[];
  },
  [ "museum:top-collections" ],
  { revalidate: REVALIDATE_SECONDS, tags: [ CACHE_TAG ] },
);

/** A single published collection by slug, with its child collections. */
export const getCollection = cache(
  unstable_cache(
    async (slug: string): Promise<Collection | null> => {
      const rows = await client().request(
        readItems("collections", {
          fields: [
            "id",
            "name",
            "title",
            "description",
            "essay",
            "slug",
            { child_collections: [ "id", "name", "slug" ] },
          ],
          filter: {
            _and: [ { status: { _eq: "published" } }, { slug: { _eq: slug } } ],
          },
          limit: 1,
        }),
      );
      return ((rows as unknown as Collection[])[0]) ?? null;
    },
    [ "museum:collection" ],
    { revalidate: REVALIDATE_SECONDS, tags: [ CACHE_TAG ] },
  ),
);

function nftFilter(slugs: string[], search?: string) {
  const base: Record<string, unknown>[] = [
    { collection_type: { slug: { _in: slugs } } },
    { media_info: { _null: false } },
    { display_media_info: { _null: false } },
  ];
  if (search && search.trim()) {
    base.push({
      _or: [
        { name: { _icontains: search.trim() } },
        { artist_name: { _icontains: search.trim() } },
      ],
    });
  }
  return { _and: base };
}

export const countNfts = unstable_cache(
  async (slugs: string[], search?: string): Promise<number> => {
    const res = await client().request(
      aggregate("nfts", {
        aggregate: { count: "*" },
        query: { filter: nftFilter(slugs, search) as never },
      }),
    );
    const count = (res as unknown as { count: number | string }[])[0]?.count;
    return Number(count) || 0;
  },
  [ "museum:count-nfts" ],
  { revalidate: REVALIDATE_SECONDS, tags: [ CACHE_TAG ] },
);

export const listNfts = unstable_cache(
  async (opts: {
    slugs: string[];
    page?: number;
    search?: string;
    limit?: number;
  }): Promise<Nft[]> => {
    const limit = opts.limit ?? NFTS_PER_PAGE;
    const page = Math.max(1, opts.page ?? 1);
    const rows = await client().request(
      readItems("nfts", {
        fields: [
          "id",
          "name",
          "artist_name",
          "collection",
          "media_info",
          "display_media_info",
          "display_animation_info",
          "response_opensea",
        ],
        filter: nftFilter(opts.slugs, opts.search) as never,
        limit,
        offset: (page - 1) * limit,
      }),
    );
    return rows as unknown as Nft[];
  },
  [ "museum:list-nfts" ],
  { revalidate: REVALIDATE_SECONDS, tags: [ CACHE_TAG ] },
);

/** A batch of candidate pieces (with media) for a collection cover/shuffle. */
export async function listCollectionPreviews(
  slugs: string[],
  count = 12,
): Promise<Nft[]> {
  try {
    return await listNfts({ slugs, limit: count });
  } catch {
    return [];
  }
}

/** Published rooms (immersive exhibitions). */
export const listRooms = unstable_cache(
  async (): Promise<Room[]> => {
    const ROOM_FIELDS = [
      "id",
      "title",
      "architect",
      "description",
      "series",
      "slots",
      "image",
      "model",
      "token_id",
    ];
    const fetchRooms = (withOptimized: boolean) =>
      client().request(
        readItems("rooms", {
          // model_optimized = builder variant (draco/webp + embedded Slot_NNN,
          // see apps/migration/embed-room-slots.ts). The field is created by
          // that script's first --write run — fall back gracefully until then.
          fields: withOptimized ? [ ...ROOM_FIELDS, "model_optimized" ] : ROOM_FIELDS,
          sort: [ "series", "title" ],
          limit: -1,
        }),
      );
    let rows;
    try {
      rows = await fetchRooms(true);
    } catch {
      rows = await fetchRooms(false);
    }
    return rows as unknown as Room[];
  },
  [ "museum:rooms" ],
  { revalidate: REVALIDATE_SECONDS, tags: [ CACHE_TAG ] },
);
