/**
 * Generates the Hyperfy app script for the MOCA museum guide — an agentic
 * VRM avatar that visitors talk to about the exhibition they're standing in.
 *
 * The app's blueprint model IS the guide's .vrm (Hyperfy renders a VRM
 * blueprint as an avatar). The script adds a nametag and a hold-E action;
 * triggering it opens a per-player world-space panel with a greeting and
 * suggested questions (clickable buttons). Free-text questions arrive
 * through the world chat (or `/ask …`) while a visitor's session is open
 * and they're standing near the guide.
 *
 * Answers are AGENTIC and per-player: the SERVER side of the script calls
 * the MOCA API (`POST /v1/guide/ask`) — which combines the registered
 * exhibition context (rooms, architects, artists, works) with the museum's
 * Cortex Library and an optional Art DeCC0 persona — and replies privately
 * via `app.sendTo`, so two visitors can quiz the guide at once without
 * seeing each other's conversations. Per-player history rides along, so the
 * guide reacts to the conversation, not just the last question.
 *
 * Baked suggestions keep the guide useful (greeting + question starters)
 * even when the museum API is unreachable; live answers then degrade to a
 * polite offline line.
 *
 * KEEP IN SYNC with apps/hyperfy/lib/guide-script.mjs — the CLI twin used
 * by spawn-exhibition.mjs.
 */

/** JSON.stringify safe to embed in a generated script. */
function inline(value: unknown): string {
  return JSON.stringify(value).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

export interface GuideScriptOptions {
  /** Stable exhibition id (registered with the guide API). */
  exhibitionId: string;
  /** Display title, e.g. "Echoes of the Mind". */
  exhibitionName: string;
  /** MOCA API base (default https://api.moca.qwellco.de). */
  apiUrl?: string;
  /** The guide's display name (default "Tsahafi"). */
  guideName?: string;
  /** Art DeCC0 token id whose persona the guide adopts (default 4209, Tsahafi). */
  decc0Id?: number;
  /** A SOUL.md the guide embodies (beats decc0/soulRef). */
  customSoul?: string;
  /** Display name for the custom soul. */
  soulName?: string;
  /** A Soulweaver soul coordinate, resolved by the API at answer time. */
  soulRef?: { chainId: number; address: string; tokenId: string } | null;
  /** Baked question starters (offline fallback). */
  suggestions?: string[];
  roomCount?: number;
  artworkCount?: number;
}

/** @returns the app script source */
export function generateGuideScript({
  exhibitionId,
  exhibitionName,
  apiUrl = "https://api.moca.qwellco.de",
  guideName = "Tsahafi",
  decc0Id = 4209,
  customSoul = "",
  soulName = "",
  soulRef = null,
  suggestions = [],
  roomCount = 0,
  artworkCount = 0,
}: GuideScriptOptions): string {
  const config = {
    exhibition: { id: exhibitionId, name: exhibitionName, rooms: roomCount, artworks: artworkCount },
    apiUrl: apiUrl.replace(/\/+$/, ""),
    guideName,
    decc0Id: Number(decc0Id) || 0,
    customSoul: String(customSoul || "").slice(0, 4000),
    soulName: String(soulName || "").slice(0, 60),
    soulRef: soulRef && soulRef.chainId && soulRef.address && soulRef.tokenId
      ? { chainId: Number(soulRef.chainId), address: String(soulRef.address), tokenId: String(soulRef.tokenId) }
      : null,
    suggestions: suggestions.slice(0, 6),
  };

  return `// MOCA museum guide — generated by the Museum of Crypto Art world builder.
// A VRM avatar that answers visitor questions about this exhibition: hold E
// to talk, click a suggested question, or just type in the chat while you
// stand near it. Answers are private to each visitor. Right-click the guide
// in build mode to change its name, persona (Art DeCC0 token id) or API.

app.configure([
  { key: 'guideName', type: 'text', label: 'Guide name', initial: ${inline(config.guideName)} },
  { key: 'decc0', type: 'number', label: 'DeCC0 persona', hint: 'Art DeCC0 token id whose soul the guide adopts (default 4209 = Tsahafi, the scholar-curator)', min: 0, max: 10000, step: 1, initial: ${inline(config.decc0Id)} },
  { key: 'customSoul', type: 'textarea', label: 'Custom SOUL', hint: 'Paste a SOUL.md and the guide embodies it (overrides the DeCC0 persona)', initial: ${inline(config.customSoul)} },
  { key: 'apiUrl', type: 'text', label: 'Museum API', hint: 'MOCA API base URL the guide asks for answers', initial: ${inline(config.apiUrl)} },
  { key: 'exhibitionId', type: 'text', label: 'Exhibition id', hint: 'The registered exhibition this guide speaks for (POST /v1/guide/exhibitions)', initial: ${inline(config.exhibition.id)} },
  { key: 'exhibitionName', type: 'text', label: 'Exhibition title', initial: ${inline(config.exhibition.name)} },
  { key: 'talkDistance', type: 'range', label: 'Talk distance', hint: 'How close visitors must be to start talking (meters)', min: 1, max: 8, step: 0.5, initial: 3 },
  { key: 'chatRange', type: 'range', label: 'Chat range', hint: 'How far the guide hears typed chat questions (meters)', min: 4, max: 30, step: 1, initial: 10 },
])

const BAKED = ${inline(config.exhibition)}
const BAKED_SUGGESTIONS = ${inline(config.suggestions)}

const str = (v, d) => (typeof v === 'string' && v.trim() ? v.trim() : d)
const numOr = (v, d) => (typeof v === 'number' && v === v ? v : d)
// Retargetable: point a dropped guide at any registered exhibition by id.
const EXHIBITION = {
  id: str(props.exhibitionId, BAKED.id),
  name: str(props.exhibitionName, BAKED.name),
  rooms: BAKED.rooms,
  artworks: BAKED.artworks,
}
const NAME = str(props.guideName, ${inline(config.guideName)})
const DECC0 = numOr(props.decc0, ${inline(config.decc0Id)})
const CUSTOM_SOUL = str(props.customSoul, ${inline(config.customSoul)})
const SOUL_NAME = ${inline(config.soulName)}
const SOUL_REF = ${inline(config.soulRef)}
const API = str(props.apiUrl, ${inline(config.apiUrl)}).replace(/\\/+$/, '')
const TALK_DIST = numOr(props.talkDistance, 3)
const CHAT_RANGE = numOr(props.chatRange, 10)

const GREETING = 'Welcome to \\u201c' + EXHIBITION.name + '\\u201d! I\\u2019m ' + NAME + ', your guide' +
  (EXHIBITION.artworks ? ' \\u2014 ' + EXHIBITION.rooms + ' room(s), ' + EXHIBITION.artworks + ' works to discover' : '') +
  '. Pick a question, or just type yours in the chat while you\\u2019re near me.'
const OFFLINE = 'My deeper knowledge is offline right now \\u2014 walk the rooms and come back to me in a little while.'

// ---------------------------------------------------------------- server ----
if (world.isServer) {
  // playerId -> { open, history: [{role,content}], suggestions, busy, lastAsk }
  const sessions = {}
  const session = (playerId) => {
    if (!sessions[playerId]) {
      sessions[playerId] = { open: false, history: [], suggestions: BAKED_SUGGESTIONS, busy: false, lastAsk: 0 }
    }
    return sessions[playerId]
  }

  function nearGuide(playerId, range) {
    try {
      const p = world.getPlayer(playerId)
      if (!p || !p.position) return false
      const dx = p.position.x - app.position.x
      const dy = p.position.y - app.position.y
      const dz = p.position.z - app.position.z
      return dx * dx + dy * dy + dz * dz <= range * range
    } catch (e) {
      return false
    }
  }

  async function handleAsk(playerId, text, viaChat) {
    const s = session(playerId)
    const now = Date.now()
    if (s.busy || now - s.lastAsk < 1500) return
    // "1"/"2"/"3" picks one of the suggestions last shown to this player.
    const digit = /^[1-9]$/.test(text) ? Number(text) : 0
    const question = digit && s.suggestions[digit - 1] ? s.suggestions[digit - 1] : text
    if (!question || question.length < 2) return
    s.busy = true
    s.lastAsk = now
    app.sendTo(playerId, 'moca:guide:thinking', { question })
    let answer = OFFLINE
    let persona = NAME
    let sources = []
    try {
      const player = world.getPlayer(playerId)
      const res = await fetch(API + '/v1/guide/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          exhibition: EXHIBITION.id,
          question: question.slice(0, 2000),
          history: s.history.slice(-8),
          decc0: DECC0 || undefined,
          soul: CUSTOM_SOUL || undefined,
          soulName: (CUSTOM_SOUL && SOUL_NAME) || undefined,
          soulRef: SOUL_REF || undefined,
          visitor: player && player.name ? String(player.name).slice(0, 48) : undefined,
        }),
      })
      if (res && res.ok) {
        const body = await res.json()
        const d = body && body.data
        if (d && d.answer) {
          answer = String(d.answer)
          persona = str(d.persona, NAME)
          if (Array.isArray(d.suggestions) && d.suggestions.length) s.suggestions = d.suggestions
          if (Array.isArray(d.sources)) sources = d.sources
        }
      }
    } catch (e) {
      console.error('[moca-guide] ask failed', e && e.message)
    }
    s.history.push({ role: 'user', content: question })
    s.history.push({ role: 'assistant', content: answer.slice(0, 2000) })
    if (s.history.length > 16) s.history.splice(0, s.history.length - 16)
    s.busy = false
    app.sendTo(playerId, 'moca:guide:answer', {
      question,
      text: answer,
      persona,
      sources,
      suggestions: s.suggestions,
      viaChat: !!viaChat,
    })
  }

  app.on('moca:guide:open', (d, playerId) => {
    const s = session(playerId)
    s.open = true
    app.sendTo(playerId, 'moca:guide:hello', { suggestions: s.suggestions })
  })
  app.on('moca:guide:close', (d, playerId) => {
    session(playerId).open = false
  })
  app.on('moca:guide:ask', (d, playerId) => {
    if (!d || typeof d.text !== 'string') return
    if (!nearGuide(playerId, Math.max(CHAT_RANGE, TALK_DIST + 2))) return
    handleAsk(playerId, d.text.trim(), false)
  })

  // Free text: chat from a visitor with an open session, standing near the
  // guide. "/ask <question>" works from anywhere in chat range, session or not.
  world.on('chat', (msg) => {
    try {
      if (!msg || !msg.fromId || typeof msg.body !== 'string') return
      const s = sessions[msg.fromId]
      if (!s || !s.open) return
      if (msg.body.startsWith('/')) return
      if (!nearGuide(msg.fromId, CHAT_RANGE)) return
      handleAsk(msg.fromId, msg.body.trim(), true)
    } catch (e) {
      console.error('[moca-guide] chat failed', e && e.message)
    }
  })
  world.on('command', (d) => {
    try {
      if (!d || !d.playerId || !Array.isArray(d.args)) return
      if (String(d.args[0]).toLowerCase() !== 'ask') return
      const text = d.args.slice(1).join(' ').trim()
      if (!text) return
      if (!nearGuide(d.playerId, CHAT_RANGE)) return
      handleAsk(d.playerId, text, true)
    } catch (e) {
      /* commands are best-effort */
    }
  })
  world.on('leave', (e) => {
    if (e && e.playerId) delete sessions[e.playerId]
  })
}

// ---------------------------------------------------------------- client ----
if (world.isClient) {
  try {
    const tag = app.create('nametag', { label: NAME })
    tag.position.set(0, 2.05, 0)
    app.add(tag)
  } catch (e) {
    /* nametags unavailable — the panel still names the guide */
  }

  // ---- the conversation panel (local to this player) ----------------------
  let panel = null
  let answerText = null
  let statusText = null
  let buttons = []
  let currentSuggestions = BAKED_SUGGESTIONS

  function ask(text) {
    app.send('moca:guide:ask', { text })
    setStatus('\\u2026 ' + NAME + ' is thinking')
  }

  function setStatus(s) {
    if (statusText) {
      try { statusText.value = s || ' ' } catch (e) {}
    }
  }

  function setAnswer(s) {
    if (answerText) {
      try { answerText.value = s.length > 1100 ? s.slice(0, 1099) + '\\u2026' : s } catch (e) {}
    }
  }

  function setSuggestions(list) {
    currentSuggestions = (list && list.length ? list : BAKED_SUGGESTIONS).slice(0, 3)
    buttons.forEach((b, i) => {
      const q = currentSuggestions[i]
      try {
        b.view.visible = !!q
        if (q) b.text.value = (i + 1) + '. ' + q
      } catch (e) {}
    })
  }

  function closePanel() {
    if (!panel) return
    try { app.remove(panel) } catch (e) {}
    panel = null
    answerText = null
    statusText = null
    buttons = []
    app.send('moca:guide:close', {})
  }

  function openPanel() {
    if (panel) return
    try {
      panel = app.create('ui', {
        space: 'world',
        width: 400,
        height: 460,
        backgroundColor: 'rgba(8, 8, 8, 0.92)',
        borderRadius: 12,
        padding: 14,
        flexDirection: 'column',
        gap: 8,
        billboard: 'y',
        doubleside: true,
      })
      panel.size = 0.0028
      panel.position.set(0, 2.5, 0)

      const header = app.create('uitext', {
        value: NAME + ' \\u00b7 \\u201c' + EXHIBITION.name + '\\u201d',
        fontSize: 15,
        color: '#ffffff',
        fontWeight: 'bold',
        lineHeight: 1.2,
      })
      panel.add(header)

      answerText = app.create('uitext', {
        value: GREETING,
        fontSize: 12.5,
        color: '#e6e6e6',
        lineHeight: 1.35,
      })
      panel.add(answerText)

      statusText = app.create('uitext', { value: ' ', fontSize: 11, color: '#9a9a9a', lineHeight: 1.2 })
      panel.add(statusText)

      buttons = []
      for (let i = 0; i < 3; i++) {
        const view = app.create('uiview', {
          backgroundColor: 'rgba(255, 255, 255, 0.08)',
          borderRadius: 8,
          padding: 8,
        })
        const text = app.create('uitext', { value: ' ', fontSize: 11.5, color: '#ffffff', lineHeight: 1.25 })
        view.add(text)
        view.cursor = 'pointer'
        ;(function (idx) {
          view.onPointerDown = () => {
            const q = currentSuggestions[idx]
            if (q) ask(q)
          }
          view.onPointerEnter = () => { try { view.backgroundColor = 'rgba(255, 255, 255, 0.16)' } catch (e) {} }
          view.onPointerLeave = () => { try { view.backgroundColor = 'rgba(255, 255, 255, 0.08)' } catch (e) {} }
        })(i)
        panel.add(view)
        buttons.push({ view, text })
      }

      const hint = app.create('uitext', {
        value: '\\u2026 or type your question in the chat (1\\u20133 picks a suggestion). Walk away to end.',
        fontSize: 10.5,
        color: '#9a9a9a',
        lineHeight: 1.25,
      })
      panel.add(hint)

      app.add(panel)
      setSuggestions(currentSuggestions)
      app.send('moca:guide:open', {})
    } catch (e) {
      console.error('[moca-guide] panel failed', e && e.message)
    }
  }

  // ---- hold E to talk ------------------------------------------------------
  try {
    const act = app.create('action')
    act.label = 'Talk to ' + NAME
    act.distance = TALK_DIST
    act.duration = 0.3
    act.onTrigger = () => {
      if (panel) closePanel()
      else openPanel()
    }
    act.position.set(0, 1.2, 0)
    app.add(act)
  } catch (e) {
    /* action nodes unavailable — chat still works once a session opens */
  }

  app.on('moca:guide:hello', (d) => {
    if (d && Array.isArray(d.suggestions)) setSuggestions(d.suggestions)
  })
  app.on('moca:guide:thinking', () => {
    setStatus('\\u2026 ' + NAME + ' is thinking')
  })
  app.on('moca:guide:answer', (d) => {
    if (!d) return
    setStatus(Array.isArray(d.sources) && d.sources.length ? 'Sources: ' + d.sources.join(' \\u00b7 ') : ' ')
    if (panel) {
      setAnswer(String(d.text || ''))
      setSuggestions(d.suggestions)
    }
    // Questions typed in chat get their answer in chat too — privately.
    if (d.viaChat || !panel) {
      try {
        const body = String(d.text || '')
        const chunks = body.match(/[\\s\\S]{1,280}/g) || []
        chunks.slice(0, 4).forEach((c) => world.chat({ from: str(d.persona, NAME), body: c }, false))
      } catch (e) {
        /* chat unavailable — the panel already shows it */
      }
    }
  })

  // Walking away ends the conversation; the guide turns to face whoever is close.
  let sinceCheck = 0
  app.on('update', (dt) => {
    sinceCheck += dt
    if (sinceCheck < 0.25) return
    sinceCheck = 0
    let me = null
    try { me = world.getPlayer() } catch (e) {}
    if (!me || !me.position) return
    const dx = me.position.x - app.position.x
    const dz = me.position.z - app.position.z
    const distSq = dx * dx + dz * dz
    if (panel && distSq > (TALK_DIST + 4) * (TALK_DIST + 4)) closePanel()
    if (distSq < 36 && distSq > 0.04) {
      try {
        const yaw = Math.atan2(dx, dz)
        app.quaternion.set(0, Math.sin(yaw / 2), 0, Math.cos(yaw / 2))
      } catch (e) {}
    }
  })
}
`;
}
