import type {
  HyperfyArtwork,
  HyperfySlot,
} from "@/components/museum/three/hyperfy-export";

/**
 * Generates the Hyperfy app script for one exhibition room.
 *
 * The script runs inside the engine's app sandbox on every client and the
 * server. Artworks hang on BAKED SLOT ANCHORS: the export carries each
 * slot's GLB-local transform + frame size (measured by the museum builder),
 * so hanging works even when the slot never exists as a GLB node —
 * un_MUSEUM rooms generate their `Auto_NNN` slots at builder runtime.
 * Authored `Slot_NNN` placeholder meshes are hidden when present. Artworks
 * are CHILD NODES of the room app — grab and move the room in build mode
 * and the whole curation moves with it.
 *
 * Sizing matches the builder: each work letterboxes into its slot frame
 * (true aspect ratio preserved) times the curator's per-slot scale. Exports
 * that predate baked slots fall back to GLB-node anchors with a metric base
 * size.
 *
 * The room is SOLID: the blueprint renders the GLB with collision 'auto' (which
 * only collides meshes the GLB tags `_collider` etc. — the museum room models
 * carry no such tags, so the rendered model alone is walk-through). We make it
 * solid by walking the loaded model (`app.traverse`) and giving each mesh a
 * STATIC trimesh collider built from its own geometry, parented to the mesh so
 * it inherits the world transform. Authored `Slot_NNN` placeholder quads become
 * thin coplanar wall colliders — negligible; auto-slot un_MUSEUM rooms generate
 * slots at runtime and carry no such quads.
 *
 * Refinement happens at two levels, both inside the engine:
 * - Room level: `app.configure` fields in the native inspector (artwork
 *   scale, wall gap, placards, lighting, video volume, slot editing); plus the
 *   whole room is resized by grabbing it in build mode and Shift+scrolling.
 * - Slot level: the embedded IN-WORLD SLOT EDITOR. With "Slot editing" on,
 *   builders/admins hold E at a work, then nudge it with the arrow keys and
 *   resize with the scroll wheel — synced live to everyone, validated
 *   server-side, persisted in the world's storage.json keyed by the entity
 *   id (deterministic across re-spawns), so refinements survive restarts,
 *   blueprint rebuilds AND museum curation updates.
 *
 * KEEP IN SYNC with apps/hyperfy/lib/room-script.mjs — the node twin behind
 * spawn-exhibition.mjs.
 */

/** JSON.stringify safe to embed in a generated script. */
function inline(value: unknown): string {
  return JSON.stringify(value).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

export function generateRoomScript({
  artworks,
  slots = [],
  artSize = 2,
  rootScale = 1,
}: {
  /**
   * Curated works; imageUrl may already be a world `asset://` url (the
   * spawner uploads curated images into the world before generating this).
   */
  artworks: HyperfyArtwork[];
  /** Baked slot anchors, GLB-local (from the exhibition export). */
  slots?: HyperfySlot[];
  /** Metric base size in meters — only for legacy exports without frames. */
  artSize?: number;
  /**
   * The uniform scale the spawner puts on the room entity (tile
   * normalization). Sizes in the script are meters; nodes live in GLB-local
   * units, so meter values are divided by rootScale before use.
   */
  rootScale?: number;
}): string {
  const config = artworks.map(a => ({
    slotId: a.slotId,
    title: a.name ?? null,
    artist: a.artist ?? null,
    ratio: a.ratio > 0 ? a.ratio : 1,
    imageUrl: a.imageUrl ?? null,
    videoUrl: a.videoUrl ?? null,
    override: a.override ?? null,
  }));
  const slotMap: Record<
    string,
    { p: [number, number, number]; q: [number, number, number, number]; w: number; h: number }
  > = {};
  for (const s of slots) {
    slotMap[s.id] = { p: s.position, q: s.quaternion, w: s.width, h: s.height };
  }

  return `// MOCA exhibition room — generated by the Museum of Crypto Art world builder.
// Curated artworks hang on baked slot anchors, matching the museum exactly.
// Refine in build mode (Tab): right-click the room for the App pane fields.
// Turn "Slot editing" on and scene admins can hold E at any work to nudge and
// resize it in place — synced live, saved in the world.

app.configure([
  { key: 'artScale', type: 'range', label: 'Artwork scale', hint: 'Multiplier on every hung work', min: 0.25, max: 3, step: 0.05, initial: 1 },
  { key: 'wallGap', type: 'range', label: 'Wall gap', hint: 'How far works float off the wall, in meters', min: 0.01, max: 0.3, step: 0.01, initial: 0.05 },
  { key: 'placards', type: 'toggle', label: 'Placards', hint: 'Title and artist under each work', trueLabel: 'Shown', falseLabel: 'Hidden', initial: true },
  { key: 'litArt', type: 'toggle', label: 'Art lighting', hint: 'Unlit shows true colors; lit reacts to world light', trueLabel: 'World lit', falseLabel: 'Unlit', initial: false },
  { key: 'videoVolume', type: 'range', label: 'Video volume', hint: 'Spatial volume of motion works', min: 0, max: 1, step: 0.05, initial: 0.5 },
  { key: 'editSlots', type: 'toggle', label: 'Slot editing', hint: 'Scene admins hold E at a work to move/resize it in place', trueLabel: 'On', falseLabel: 'Off', initial: true },
])

// ---- room collider -----------------------------------------------------
// The blueprint renders the room GLB with collision 'auto' (no colliders on
// untagged meshes), so the room is walk-through. Make it solid by walking the
// loaded model and giving each mesh a STATIC trimesh collider: a rigidbody +
// geometry collider parented to the mesh, so it inherits that mesh's world
// transform and reuses its geometry. Scales with the room entity.
// (NB: app.create('model', { collision }) is NOT a runtime node in this engine —
// 'model' is a blueprint-level component only; the traversal below is the
// supported in-script path.)
try {
  let madeColliders = 0
  app.traverse((node) => {
    if (madeColliders >= 2000 || !node || !node.geometry) return
    try {
      const body = app.create('rigidbody', { type: 'static' })
      body.add(app.create('collider', { type: 'geometry', geometry: node.geometry, convex: false }))
      node.add(body)
      madeColliders++
    } catch (e) {}
  })
  if (madeColliders) console.log('[moca] room solid \\u2014 ' + madeColliders + ' mesh collider(s)')
  else console.warn('[moca] room collider: no mesh geometry found to collide')
} catch (e) {
  console.error('[moca] room collider failed', e && e.message)
}

// Baked slot anchors (GLB-local) + the curated works that hang on them.
const SLOTS = ${inline(slotMap)}
const ARTWORKS = ${inline(config)}

// The room entity is uniformly scaled by the spawner (tile normalization);
// nodes live in GLB-local units, so meters are converted via M.
const M = ${1 / (Number(rootScale) || 1)}
// Metric base size for legacy exports without baked slot frames.
const LEGACY_ART_M = ${Number(artSize) || 2}

const num = (v, d) => (typeof v === 'number' && v === v ? v : d)
const bool = (v, d) => (typeof v === 'boolean' ? v : d)
const clampN = (v, lo, hi) => Math.min(hi, Math.max(lo, v))
const ART_SCALE = num(props.artScale, 1)
const WALL_GAP = num(props.wallGap, 0.05)
const PLACARDS = bool(props.placards, true)
const LIT = bool(props.litArt, false)
const VOLUME = num(props.videoVolume, 0.5)
const EDIT_SLOTS = bool(props.editSlots, true)

// In-world refinements persist under the entity id — deterministic across
// re-spawns, so they survive curation updates, rebuilds and restarts.
const STORE_KEY = 'moca:slots:' + app.instanceId
// Same clamps as the museum builder (GLB-local units).
const SCALE_MIN = 0.35
const SCALE_MAX = 3
const limX = (w) => Math.max((w || 1) * 2, 2)
const limY = (h) => Math.max((h || 1) * 0.9, 1)

// Letterbox a work (w/h ratio) into a slot frame — same as the museum.
function fit(ratio, fw, fh) {
  const r = ratio > 0 ? ratio : 1
  if (r >= fw / fh) return { w: fw, h: fw / r }
  return { w: fh * r, h: fh }
}

// Resolve where a work hangs: prefer the baked anchor (always present in
// current exports, the ONLY option for runtime-generated Auto_NNN slots);
// hide the authored placeholder mesh if the GLB carries one.
function anchorFor(slotId) {
  const glbNode = app.get(slotId)
  if (glbNode) {
    try { glbNode.visible = false } catch (e) {}
  }
  const baked = SLOTS[slotId]
  if (baked) {
    const g = app.create('group')
    g.position.set(baked.p[0], baked.p[1], baked.p[2])
    g.quaternion.set(baked.q[0], baked.q[1], baked.q[2], baked.q[3])
    app.add(g)
    return { node: g, baked, parentable: true }
  }
  if (glbNode) return { node: glbNode, baked: null, parentable: false }
  return null
}

function makePlacard(title, artist) {
  if (!title && !artist) return null
  try {
    const ui = app.create('ui', {
      space: 'world',
      width: 240,
      height: 60,
      backgroundColor: 'rgba(8, 8, 8, 0.85)',
      borderRadius: 8,
      padding: 10,
      flexDirection: 'column',
      justifyContent: 'center',
      gap: 3,
      doubleside: true,
      pointerEvents: false,
    })
    ui.size = 0.0024 * M
    if (title) {
      ui.add(app.create('uitext', { value: title, fontSize: 14, color: '#ffffff', fontWeight: 'bold', lineHeight: 1.15 }))
    }
    if (artist) {
      ui.add(app.create('uitext', { value: artist, fontSize: 11, color: '#b3b3b3', lineHeight: 1.1 }))
    }
    return ui
  } catch (e) {
    return null // older engines without ui nodes — art still hangs fine
  }
}

// slotId -> { adj, baked, title } — the in-world editor adjusts these.
const HUNG = {}
// While the local player edits a slot, remote echoes for it are ignored.
let EDITING_SLOT = null

for (const art of ARTWORKS) {
  try {
    const ov = art.override || {}
    const dx = num(ov.dx, 0)
    const dy = num(ov.dy, 0)
    const ovScale = num(ov.scale, 1)
    const ratio = art.ratio > 0 ? art.ratio : 1

    const anchor = anchorFor(art.slotId)

    // Builder-fidelity sizing: letterbox into the baked frame; legacy
    // exports (no frame data) hang at a metric base size instead.
    let width, height
    if (anchor && anchor.baked) {
      const base = fit(ratio, anchor.baked.w, anchor.baked.h)
      width = base.w * ovScale * ART_SCALE
      height = base.h * ovScale * ART_SCALE
    } else {
      width = (ratio >= 1 ? LEGACY_ART_M : LEGACY_ART_M * ratio) * ovScale * ART_SCALE * M
      height = (ratio >= 1 ? LEGACY_ART_M / ratio : LEGACY_ART_M) * ovScale * ART_SCALE * M
    }

    let node = null
    if (art.videoUrl) {
      node = app.create('video', {
        src: art.videoUrl,
        width,
        height,
        loop: true,
        volume: VOLUME,
        spatial: true,
        doubleside: true,
      })
    } else if (art.imageUrl) {
      node = app.create('image', {
        src: art.imageUrl,
        width,
        height,
        fit: 'contain',
        lit: LIT,
        doubleside: true,
      })
    }
    if (!node) continue

    const placard = PLACARDS ? makePlacard(art.title, art.artist) : null

    if (anchor) {
      try {
        // anchor (baked transform) -> adj (in-world refinement) -> art.
        const adj = app.create('group')
        anchor.node.add(adj)
        adj.add(node)
        node.position.set(dx, dy, WALL_GAP * M)
        if (placard) {
          adj.add(placard)
          placard.position.set(dx, dy - height / 2 - 0.16 * M, (WALL_GAP + 0.01) * M)
        }
        HUNG[art.slotId] = { adj, baked: anchor.baked, title: art.title, plac: placard, artH: height }
      } catch (e) {
        // Some GLB nodes can't parent — fall back to the anchor's local spot.
        app.add(node)
        node.position.set(anchor.node.position.x + dx, anchor.node.position.y + dy, anchor.node.position.z)
        node.quaternion.copy(anchor.node.quaternion)
        if (placard) {
          app.add(placard)
          placard.position.set(anchor.node.position.x + dx, anchor.node.position.y + dy - height / 2 - 0.16 * M, anchor.node.position.z)
          placard.quaternion.copy(anchor.node.quaternion)
        }
      }
    } else {
      app.add(node)
      if (placard) {
        app.add(placard)
        placard.position.set(0, -height / 2 - 0.16 * M, 0.01 * M)
      }
    }

    if (art.videoUrl && world.isClient) {
      try { node.play() } catch (e) {}
    }
  } catch (e) {
    console.error('[moca] artwork failed', art.slotId, e && e.message)
  }
}

// ---- placard anti-overlap ----------------------------------------------
// Works can hang close enough that their labels collide. Within this room
// (rooms sit on separate tiles, so cross-room overlap can't happen), any two
// placards on the same wall that would intersect get staggered: the second
// one steps down until every label reads clean.
try {
  const entries = []
  for (const id in HUNG) {
    const h = HUNG[id]
    if (h.plac && h.baked) entries.push(h)
  }
  const W = 0.62 * M // placard width in GLB-local units (240px × ui.size)
  const STEP = 0.3 * M
  for (let i = 0; i < entries.length; i++) {
    for (let j = i + 1; j < entries.length; j++) {
      const a = entries[i]
      const b = entries[j]
      const qa = a.baked.q
      const qb = b.baked.q
      const facing = qa[0] * qb[0] + qa[1] * qb[1] + qa[2] * qb[2] + qa[3] * qb[3]
      if (Math.abs(facing) < 0.92) continue // different walls
      const ddx = a.baked.p[0] - b.baked.p[0]
      const ddz = a.baked.p[2] - b.baked.p[2]
      if (Math.sqrt(ddx * ddx + ddz * ddz) > W) continue
      const ya = a.baked.p[1] - a.artH / 2
      const yb = b.baked.p[1] - b.artH / 2
      if (Math.abs(ya - yb) > STEP) continue
      try { b.plac.position.y -= STEP } catch (e) {}
    }
  }
} catch (e) {
  /* labels may overlap on exotic GLBs — never break the hang */
}

// ---- in-world slot refinement -----------------------------------------
// Adjustments are { dx, dy, s } per slot, layered ON TOP of the museum
// curation via the adj group. Server owns the truth: it validates sender
// rank, clamps, persists to world storage and rebroadcasts.

function applyAdjust(slotId, a) {
  const h = HUNG[slotId]
  if (!h) return
  const dx = a ? num(a.dx, 0) : 0
  const dy = a ? num(a.dy, 0) : 0
  const s = a ? clampN(num(a.s, 1), SCALE_MIN, SCALE_MAX) : 1
  h.adj.position.set(dx, dy, 0)
  h.adj.scale.set(s, s, s)
}

function sanitizeAdjust(d) {
  const h = HUNG[d.slot]
  const w = h && h.baked ? h.baked.w : 2
  const ht = h && h.baked ? h.baked.h : 2
  return {
    slot: d.slot,
    dx: clampN(num(d.dx, 0), -limX(w), limX(w)),
    dy: clampN(num(d.dy, 0), -limY(ht), limY(ht)),
    s: clampN(num(d.s, 1), SCALE_MIN, SCALE_MAX),
  }
}

if (world.isServer) {
  let saved = world.get(STORE_KEY) || {}
  app.state.adjust = saved
  // After a rebuild (props/curation update) connected clients lost their
  // state — rebroadcast the persisted refinements.
  app.send('moca:adjust:init', saved)
  app.on('moca:adjust', (data, networkId) => {
    try {
      const p = world.getPlayer(networkId)
      // Only SCENE ADMINS may move/resize works — not every build-rights player.
      if (!p || !p.admin) return
      if (!data || typeof data.slot !== 'string' || !HUNG[data.slot]) return
      if (data.reset) {
        delete saved[data.slot]
      } else {
        const a = sanitizeAdjust(data)
        saved[data.slot] = { dx: a.dx, dy: a.dy, s: a.s }
      }
      world.set(STORE_KEY, saved)
      app.state.adjust = saved
      app.send('moca:adjust', data.reset ? { slot: data.slot, reset: true } : saved[data.slot] && { slot: data.slot, ...saved[data.slot] })
    } catch (e) {
      console.error('[moca] adjust failed', e && e.message)
    }
  })
}

if (world.isClient) {
  // Late joiners get the persisted refinements via the entity snapshot.
  const initial = (app.state && app.state.adjust) || {}
  for (const slotId in initial) applyAdjust(slotId, initial[slotId])
  app.on('moca:adjust:init', (map) => {
    for (const slotId in HUNG) {
      if (slotId !== EDITING_SLOT) applyAdjust(slotId, map && map[slotId])
    }
  })
  app.on('moca:adjust', (d) => {
    if (d && d.slot && d.slot !== EDITING_SLOT) applyAdjust(d.slot, d.reset ? null : d)
  })

  // ---- the editor: hold E at a work, arrows nudge, scroll resizes ------
  let me = null
  try { me = world.getPlayer() } catch (e) {}
  if (EDIT_SLOTS && me && me.admin) {
    const live = {}
    for (const slotId in initial) live[slotId] = { ...initial[slotId] }

    let editing = null // { slotId, control, panel, sendTimer }

    function makeHelpPanel(title) {
      try {
        const ui = app.create('ui', {
          space: 'world',
          width: 270,
          height: 92,
          backgroundColor: 'rgba(8, 8, 8, 0.92)',
          borderRadius: 10,
          padding: 12,
          flexDirection: 'column',
          justifyContent: 'center',
          gap: 4,
          billboard: 'y',
          doubleside: true,
          pointerEvents: false,
        })
        ui.size = 0.0036 * M
        ui.add(app.create('uitext', { value: 'Editing — ' + (title || 'artwork'), fontSize: 13, color: '#ffffff', fontWeight: 'bold' }))
        ui.add(app.create('uitext', { value: 'Arrows move · Shift = faster · scroll resizes', fontSize: 11, color: '#b3b3b3' }))
        ui.add(app.create('uitext', { value: 'R resets · Enter or Esc finishes', fontSize: 11, color: '#b3b3b3' }))
        return ui
      } catch (e) {
        return null
      }
    }

    function endEdit(commit) {
      if (!editing) return
      const { slotId, control, panel } = editing
      try { HUNG[slotId].adj.rotation.z = 0 } catch (e) {}
      const hp = HUNG[slotId] && HUNG[slotId].plac
      if (hp) { try { hp.visible = true } catch (e) {} }
      try { if (panel) HUNG[slotId].adj.remove(panel) } catch (e) {}
      try { control.release() } catch (e) {}
      if (commit) sendAdjust(slotId)
      editing = null
      EDITING_SLOT = null
    }

    function sendAdjust(slotId) {
      const a = live[slotId]
      if (a) app.send('moca:adjust', { slot: slotId, dx: a.dx, dy: a.dy, s: a.s })
    }

    function startEdit(slotId) {
      endEdit(true)
      const h = HUNG[slotId]
      if (!h) return
      if (!live[slotId]) live[slotId] = { dx: 0, dy: 0, s: 1 }
      const control = app.control()
      for (const k of ['arrowUp', 'arrowDown', 'arrowLeft', 'arrowRight', 'enter', 'escape', 'keyR']) {
        try { control[k].capture = true } catch (e) {}
      }
      try { control.scrollDelta.capture = true } catch (e) {}
      // The help panel replaces the placard while editing — never both.
      if (h.plac) { try { h.plac.visible = false } catch (e) {} }
      const panel = makeHelpPanel(h.title)
      if (panel) {
        h.adj.add(panel)
        // Keep the how-to readable: near the work's top edge but never
        // higher than ~eye-and-a-bit, even for huge pieces.
        const ph = h.baked ? h.baked.h : 2
        panel.position.set(0, Math.min(ph * 0.5 + 0.4 * M, 1.5 * M), (WALL_GAP + 0.12) * M)
      }
      // A quick wiggle says "this one is active now".
      editing = { slotId, control, panel, sinceSend: 0, dirty: false, wiggle: 0.5 }
      EDITING_SLOT = slotId
    }

    app.on('update', (dt) => {
      if (!editing) return
      const { slotId, control } = editing
      const a = live[slotId]
      const h = HUNG[slotId]
      if (!a || !h || !control) { endEdit(false); return }

      // Activation wiggle: a damped shake on the work so the selection is
      // unmistakable, settling back to exactly where it was.
      if (editing.wiggle > 0) {
        editing.wiggle -= dt
        const left = Math.max(editing.wiggle, 0)
        try {
          h.adj.rotation.z = Math.sin((0.5 - left) * 26) * 0.07 * (left / 0.5)
          if (left <= 0) h.adj.rotation.z = 0
        } catch (e) {}
      }

      const fast = (control.shiftLeft && control.shiftLeft.down) || (control.shiftRight && control.shiftRight.down)
      const speed = (fast ? 1.8 : 0.45) * M * dt
      let changed = false
      if (control.arrowLeft.down) { a.dx -= speed; changed = true }
      if (control.arrowRight.down) { a.dx += speed; changed = true }
      if (control.arrowUp.down) { a.dy += speed; changed = true }
      if (control.arrowDown.down) { a.dy -= speed; changed = true }
      const scroll = control.scrollDelta.value
      if (scroll) { a.s = a.s * (1 - scroll * 0.002); changed = true }
      if (control.keyR.pressed) {
        live[slotId] = { dx: 0, dy: 0, s: 1 }
        applyAdjust(slotId, null)
        app.send('moca:adjust', { slot: slotId, reset: true })
        editing.dirty = false
        return
      }
      if (changed) {
        const w = h.baked ? h.baked.w : 2
        const ht = h.baked ? h.baked.h : 2
        a.dx = clampN(a.dx, -limX(w), limX(w))
        a.dy = clampN(a.dy, -limY(ht), limY(ht))
        a.s = clampN(a.s, SCALE_MIN, SCALE_MAX)
        applyAdjust(slotId, a)
        editing.dirty = true
      }
      // Throttled live sync while editing; final send on finish.
      editing.sinceSend += dt
      if (editing.dirty && editing.sinceSend > 0.2) {
        sendAdjust(slotId)
        editing.sinceSend = 0
        editing.dirty = false
      }
      if (control.enter.pressed || control.escape.pressed) endEdit(true)
    })

    // Keep the editor's view of refinements in sync with other editors.
    app.on('moca:adjust', (d) => {
      if (!d || !d.slot) return
      if (editing && editing.slotId === d.slot) return // ours
      live[d.slot] = d.reset ? { dx: 0, dy: 0, s: 1 } : { dx: num(d.dx, 0), dy: num(d.dy, 0), s: num(d.s, 1) }
    })

    // The "Adjust artwork" action is a BUILD-MODE tool. We create the actions
    // but only attach them while the admin is in build mode (Tab) — in normal
    // play an admin behaves exactly like a regular visitor (no edit prompt). The
    // engine emits 'build-mode' on every toggle; it starts off at load.
    const editActions = []
    for (const slotId in HUNG) {
      try {
        const h = HUNG[slotId]
        const act = app.create('action')
        act.label = 'Adjust artwork'
        act.distance = 4
        act.duration = 0.4
        act.position.set(0, 0, (WALL_GAP + 0.1) * M)
        act.onTrigger = () => {
          if (editing && editing.slotId === slotId) endEdit(true)
          else startEdit(slotId)
        }
        editActions.push({ act, adj: h.adj })
      } catch (e) {
        // action nodes unavailable — inspector fields still work
      }
    }
    let inBuild = false
    function showEditActions(on) {
      on = !!on
      if (on === inBuild) return
      inBuild = on
      for (const e of editActions) {
        try { if (on) e.adj.add(e.act); else e.adj.remove(e.act) } catch (err) {}
      }
      if (!on) endEdit(false) // leaving build mode ends any active edit
    }
    try { world.on('build-mode', showEditActions) } catch (e) {}
    // (starts hidden — build mode is off on load)
  }
}
`;
}
