/**
 * Generates the Hyperfy app script for the MOCA museum guide — a walking,
 * talking VRM avatar that visitors talk to about the exhibition they're in.
 *
 * The script owns the guide's body as an `avatar` node (the blueprint model is
 * null), so it can drive locomotion + gesture emotes as the guide follows the
 * visitor. A single billboarded speech bubble above the head greets the visitor,
 * shows clickable artwork questions, types out answers, and (when enabled) the
 * guide speaks them aloud via an audio node fed by the guide API's TTS.
 *
 * Answers are AGENTIC and per-player: the SERVER side of the script calls
 * the MOCA API (`POST /v1/guide/ask`) — which combines the registered
 * exhibition context (rooms, architects, artists, works) with the museum's
 * Cortex Library and an optional Art DeCC0 persona — and replies privately
 * via `app.sendTo`, so two visitors can quiz the guide at once without
 * seeing each other's conversations. Per-player history rides along, so the
 * guide reacts to the conversation, not just the last question.
 *
 * Baked suggestions keep the guide useful (greeting + question starters)
 * even when the museum API is unreachable; live answers then degrade to a
 * polite offline line.
 *
 * KEEP IN SYNC with apps/museum/src/lib/museum/hyperfy/guide-script.ts —
 * the browser twin used by the "Spawn to Hyperfy" dialog.
 */

/** JSON.stringify safe to embed in a generated script. */
function inline(value) {
  return JSON.stringify(value).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

/**
 * @param {object} opts
 * @param {string} opts.exhibitionId   stable exhibition id (registered with the guide API)
 * @param {string} opts.exhibitionName display title, e.g. "Echoes of the Mind"
 * @param {string} [opts.apiUrl]       MOCA API base (default https://api.moca.qwellco.de)
 * @param {string} [opts.guideName]    the guide's display name (default "Oblak")
 * @param {number} [opts.decc0Id]      Art DeCC0 token id whose persona the guide adopts (default 2875, Oblak)
 * @param {string} [opts.customSoul]   a SOUL.md the guide embodies (beats decc0/soulRef)
 * @param {string} [opts.soulName]     display name for the custom soul
 * @param {{chainId:number,address:string,tokenId:string}|null} [opts.soulRef]
 *   a Soulweaver soul coordinate, resolved by the API at answer time
 * @param {string[]} [opts.suggestions] baked question starters (offline fallback)
 * @param {number} [opts.roomCount]
 * @param {number} [opts.artworkCount]
 * @param {string} [opts.avatarUrl]    the .vrm body the script animates (asset/absolute URL)
 * @param {boolean} [opts.speak]       speak answers aloud in-world (default true)
 * @param {string} [opts.voice]        Venice TTS voice id (empty = API default)
 * @returns {string} the app script source
 */
export function generateGuideScript({
  exhibitionId,
  exhibitionName,
  apiUrl = "https://api.moca.qwellco.de",
  guideName = "Oblak",
  decc0Id = 2875,
  customSoul = "",
  soulName = "",
  soulRef = null,
  suggestions = [],
  roomCount = 0,
  artworkCount = 0,
  avatarUrl = "",
  speak = true,
  voice = "",
}) {
  const config = {
    exhibition: { id: exhibitionId, name: exhibitionName, rooms: roomCount, artworks: artworkCount },
    apiUrl: apiUrl.replace(/\/+$/, ""),
    guideName,
    decc0Id: Number(decc0Id) || 0,
    customSoul: String(customSoul || "").slice(0, 4000),
    soulName: String(soulName || "").slice(0, 60),
    soulRef: soulRef && soulRef.chainId && soulRef.address && soulRef.tokenId
      ? { chainId: Number(soulRef.chainId), address: String(soulRef.address), tokenId: String(soulRef.tokenId) }
      : null,
    suggestions: suggestions.slice(0, 6),
    avatarUrl: String(avatarUrl || ""),
    speak: speak !== false,
    voice: String(voice || "").slice(0, 40),
  };

  return `// MOCA museum guide — generated by the Museum of Crypto Art world builder.
// A walking, talking VRM avatar that answers visitor questions about this
// exhibition. It greets you from a speech bubble above its head, follows you
// once you engage, and (when enabled) speaks its answers aloud. Hold E, click a
// suggested question, or just type in the chat while near it. Answers are
// private per visitor. Right-click in build mode to change name/persona/API.

app.configure([
  { key: 'guideName', type: 'text', label: 'Guide name', initial: ${inline(config.guideName)} },
  { key: 'decc0', type: 'number', label: 'DeCC0 persona', hint: 'Art DeCC0 token id whose soul the guide adopts (default 2875 = Oblak, the cryptoart guide)', min: 0, max: 10000, step: 1, initial: ${inline(config.decc0Id)} },
  { key: 'customSoul', type: 'textarea', label: 'Custom SOUL', hint: 'Paste a SOUL.md and the guide embodies it (overrides the DeCC0 persona)', initial: ${inline(config.customSoul)} },
  { key: 'apiUrl', type: 'text', label: 'Museum API', hint: 'MOCA API base URL the guide asks for answers', initial: ${inline(config.apiUrl)} },
  { key: 'exhibitionId', type: 'text', label: 'Exhibition id', hint: 'The registered exhibition this guide speaks for (POST /v1/guide/exhibitions)', initial: ${inline(config.exhibition.id)} },
  { key: 'exhibitionName', type: 'text', label: 'Exhibition title', initial: ${inline(config.exhibition.name)} },
  { key: 'avatarUrl', type: 'text', label: 'Avatar (.vrm)', hint: 'The VRM body the guide animates (asset or absolute URL)', initial: ${inline(config.avatarUrl)} },
  { key: 'speak', type: 'toggle', label: 'Speak answers', hint: 'Read answers aloud in-world (Venice TTS via the guide API)', trueLabel: 'On', falseLabel: 'Off', initial: ${inline(config.speak)} },
  { key: 'voice', type: 'text', label: 'Voice', hint: 'Venice TTS voice id (empty = default). e.g. Serena, Vivian, Dylan', initial: ${inline(config.voice)} },
  { key: 'talkDistance', type: 'range', label: 'Talk distance', hint: 'How close visitors must be to start talking (meters)', min: 1, max: 8, step: 0.5, initial: 3 },
  { key: 'chatRange', type: 'range', label: 'Chat range', hint: 'How far the guide hears typed chat questions (meters)', min: 4, max: 30, step: 1, initial: 10 },
])

const BAKED = ${inline(config.exhibition)}
const BAKED_SUGGESTIONS = ${inline(config.suggestions)}

const str = (v, d) => (typeof v === 'string' && v.trim() ? v.trim() : d)
const numOr = (v, d) => (typeof v === 'number' && v === v ? v : d)
// Retargetable: point a dropped guide at any registered exhibition by id.
const EXHIBITION = {
  id: str(props.exhibitionId, BAKED.id),
  name: str(props.exhibitionName, BAKED.name),
  rooms: BAKED.rooms,
  artworks: BAKED.artworks,
}
const NAME = str(props.guideName, ${inline(config.guideName)})
const DECC0 = numOr(props.decc0, ${inline(config.decc0Id)})
const CUSTOM_SOUL = str(props.customSoul, ${inline(config.customSoul)})
const SOUL_NAME = ${inline(config.soulName)}
const SOUL_REF = ${inline(config.soulRef)}
const API = str(props.apiUrl, ${inline(config.apiUrl)}).replace(/\\/+$/, '')
const AVATAR_URL = str(props.avatarUrl, ${inline(config.avatarUrl)})
const SPEAK = props.speak !== false
const VOICE = str(props.voice, ${inline(config.voice)})
const TALK_DIST = numOr(props.talkDistance, 3)
const CHAT_RANGE = numOr(props.chatRange, 10)

const GREETING = 'Welcome to \\u201c' + EXHIBITION.name + '\\u201d! I\\u2019m ' + NAME + ', your guide' +
  (EXHIBITION.artworks ? ' \\u2014 ' + EXHIBITION.rooms + ' room(s), ' + EXHIBITION.artworks + ' works to discover' : '') +
  '. Pick a question below, or just type yours in the chat while you\\u2019re near me.'
const OFFLINE = 'My deeper knowledge is offline right now \\u2014 walk the rooms and come back to me in a little while.'

// Follow behaviour: after a visitor interacts (hold E or asks a question) the
// guide trails them. Hyperfy doesn't network script-driven transforms, so BOTH
// the server and every client run this SAME math against the followed player's
// (networked, so shared) position — the server so its proximity/chat-range
// checks track the visitor it's walking with, the clients for the visual. No
// transform replication needed; they agree because the input is the same.
const FOLLOW_STANDOFF = 1.8
const FOLLOW_LERP = 2.6
function moveGuide(dt, followId, home) {
  const A = app.position
  if (followId) {
    let p = null
    try { p = world.getPlayer(followId) } catch (e) {}
    if (p && p.position) {
      const dx = p.position.x - A.x
      const dz = p.position.z - A.z
      const dist = Math.sqrt(dx * dx + dz * dz) || 0.0001
      let tx = A.x
      let tz = A.z
      if (dist > FOLLOW_STANDOFF) {
        tx = p.position.x - (dx / dist) * FOLLOW_STANDOFF
        tz = p.position.z - (dz / dist) * FOLLOW_STANDOFF
      }
      const k = Math.min(1, FOLLOW_LERP * dt)
      app.position.set(A.x + (tx - A.x) * k, A.y + (p.position.y - A.y) * k, A.z + (tz - A.z) * k)
      const yaw = Math.atan2(p.position.x - app.position.x, p.position.z - app.position.z) + Math.PI
      app.quaternion.set(0, Math.sin(yaw / 2), 0, Math.cos(yaw / 2))
      return true
    }
  }
  if (home) {
    const k = Math.min(1, FOLLOW_LERP * dt)
    app.position.set(A.x + (home.x - A.x) * k, A.y + (home.y - A.y) * k, A.z + (home.z - A.z) * k)
  }
  return false
}

// ---------------------------------------------------------------- server ----
if (world.isServer) {
  // Whoever last interacts becomes the follow target (broadcast to clients via
  // app.send; mirrored to app.state.follow so late-joiners pick it up).
  const HOME = { x: app.position.x, y: app.position.y, z: app.position.z }
  let followId = null
  function setFollow(id) {
    if (id == null || followId === id) return
    followId = id
    try { app.state.follow = id } catch (e) {}
    app.send('moca:guide:follow', { id })
  }
  function clearFollow(id) {
    if (id != null && followId !== id) return
    followId = null
    try { app.state.follow = null } catch (e) {}
    app.send('moca:guide:follow', { id: null })
  }
  // playerId -> { open, history: [{role,content}], suggestions, busy, lastAsk }
  const sessions = {}
  const session = (playerId) => {
    if (!sessions[playerId]) {
      sessions[playerId] = { open: false, history: [], suggestions: BAKED_SUGGESTIONS, busy: false, lastAsk: 0 }
    }
    return sessions[playerId]
  }

  function nearGuide(playerId, range) {
    try {
      const p = world.getPlayer(playerId)
      if (!p || !p.position) return false
      const dx = p.position.x - app.position.x
      const dy = p.position.y - app.position.y
      const dz = p.position.z - app.position.z
      return dx * dx + dy * dy + dz * dz <= range * range
    } catch (e) {
      return false
    }
  }

  async function handleAsk(playerId, text, viaChat) {
    const s = session(playerId)
    const now = Date.now()
    if (s.busy || now - s.lastAsk < 1500) return
    // "1"/"2"/"3" picks one of the suggestions last shown to this player.
    const digit = /^[1-9]$/.test(text) ? Number(text) : 0
    const question = digit && s.suggestions[digit - 1] ? s.suggestions[digit - 1] : text
    if (!question || question.length < 2) return
    setFollow(playerId)
    s.busy = true
    s.lastAsk = now
    app.sendTo(playerId, 'moca:guide:thinking', { question })
    let answer = OFFLINE
    let persona = NAME
    let sources = []
    let audioUrl = null
    try {
      const player = world.getPlayer(playerId)
      const res = await fetch(API + '/v1/guide/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          exhibition: EXHIBITION.id,
          question: question.slice(0, 2000),
          history: s.history.slice(-8),
          decc0: DECC0 || undefined,
          soul: CUSTOM_SOUL || undefined,
          soulName: (CUSTOM_SOUL && SOUL_NAME) || undefined,
          soulRef: SOUL_REF || undefined,
          speak: SPEAK,
          voice: VOICE || undefined,
          visitor: player && player.name ? String(player.name).slice(0, 48) : undefined,
        }),
      })
      if (res && res.ok) {
        const body = await res.json()
        const d = body && body.data
        if (d && d.answer) {
          answer = String(d.answer)
          persona = str(d.persona, NAME)
          if (Array.isArray(d.suggestions) && d.suggestions.length) s.suggestions = d.suggestions
          if (Array.isArray(d.sources)) sources = d.sources
          if (typeof d.audioUrl === 'string') audioUrl = d.audioUrl
        }
      }
    } catch (e) {
      console.error('[moca-guide] ask failed', e && e.message)
    }
    s.history.push({ role: 'user', content: question })
    s.history.push({ role: 'assistant', content: answer.slice(0, 2000) })
    if (s.history.length > 16) s.history.splice(0, s.history.length - 16)
    s.busy = false
    app.sendTo(playerId, 'moca:guide:answer', {
      question,
      text: answer,
      persona,
      sources,
      audioUrl,
      suggestions: s.suggestions,
      viaChat: !!viaChat,
    })
  }

  app.on('moca:guide:open', (d, playerId) => {
    const s = session(playerId)
    s.open = true
    setFollow(playerId)
    app.sendTo(playerId, 'moca:guide:hello', { suggestions: s.suggestions })
  })
  app.on('moca:guide:close', (d, playerId) => {
    session(playerId).open = false
  })
  app.on('moca:guide:ask', (d, playerId) => {
    if (!d || typeof d.text !== 'string') return
    if (!nearGuide(playerId, Math.max(CHAT_RANGE, TALK_DIST + 2))) return
    handleAsk(playerId, d.text.trim(), false)
  })

  // Free text: any chat from a visitor standing near the guide is a question
  // — no panel needed, exactly what the greeting promises. Typing "1"-"3"
  // picks an offered question. "/ask <question>" also works.
  world.on('chat', (msg) => {
    try {
      if (!msg || !msg.fromId || typeof msg.body !== 'string') return
      if (msg.body.startsWith('/')) return
      if (!nearGuide(msg.fromId, CHAT_RANGE)) return
      handleAsk(msg.fromId, msg.body.trim(), true)
    } catch (e) {
      console.error('[moca-guide] chat failed', e && e.message)
    }
  })
  world.on('command', (d) => {
    try {
      if (!d || !d.playerId || !Array.isArray(d.args)) return
      if (String(d.args[0]).toLowerCase() !== 'ask') return
      const text = d.args.slice(1).join(' ').trim()
      if (!text) return
      if (!nearGuide(d.playerId, CHAT_RANGE)) return
      handleAsk(d.playerId, text, true)
    } catch (e) {
      /* commands are best-effort */
    }
  })
  world.on('leave', (e) => {
    if (e && e.playerId) {
      delete sessions[e.playerId]
      clearFollow(e.playerId)
    }
  })
  // Server-authoritative motion so chat-range/proximity track the followed
  // visitor (clients run the identical math for the visual). Eases back to its
  // post when no one's being followed.
  app.on('fixedUpdate', (dt) => {
    try { moveGuide(dt, followId, HOME) } catch (e) {}
  })
}

// ---------------------------------------------------------------- client ----
if (world.isClient) {
  // The guide's resting post + who it's currently following (server tells us).
  const HOME = { x: app.position.x, y: app.position.y, z: app.position.z }
  let followId = (app.state && app.state.follow) || null
  app.on('moca:guide:follow', (d) => { followId = d && d.id != null ? d.id : null })

  // ---- the body: a script-owned avatar we can animate ----------------------
  // The blueprint model is null, so the script owns the body via an avatar node
  // and drives the engine's built-in emote clips for locomotion + gesture.
  const EMOTE = {
    idle: 'asset://mp-idle.glb',
    walk: 'asset://mp-walk.glb?s=1.5',
    talk: 'asset://emote-talk.glb',
    float: 'asset://emote-float.glb',
  }
  let body = null
  let curEmote = null
  function setEmote(url) {
    if (!body || url === curEmote) return
    curEmote = url
    try { body.emote = url } catch (e) {}
  }
  if (AVATAR_URL) {
    try {
      body = app.create('avatar', { src: AVATAR_URL })
      app.add(body)
      setEmote(EMOTE.idle)
    } catch (e) {
      console.error('[moca-guide] avatar failed', e && e.message)
    }
  }

  try {
    const tag = app.create('nametag', { label: NAME })
    tag.position.set(0, 2.15, 0)
    app.add(tag)
  } catch (e) {
    /* nametags unavailable — the bubble still names the guide */
  }

  // ---- voice: an audio node that plays each synthesized answer --------------
  let audio = null
  function speakAnswer(url) {
    if (!SPEAK || !url) return
    try {
      if (audio) {
        try { audio.stop() } catch (e) {}
        try { app.remove(audio) } catch (e) {}
        audio = null
      }
      audio = app.create('audio', { src: url, spatial: true, volume: 1, loop: false })
      app.add(audio)
      audio.play()
    } catch (e) {
      console.error('[moca-guide] audio failed', e && e.message)
    }
  }

  // ---- conversation state ---------------------------------------------------
  let mode = 'idle'       // idle | thinking | talking
  let thinkT = 0
  let fullAnswer = ''
  let shownChars = 0
  let bodyText = null
  let suggestViews = []
  let currentSuggestions = BAKED_SUGGESTIONS
  const MAX_BUBBLE_CHARS = 1100

  function thinkingLine() {
    const dots = '.'.repeat(1 + (Math.floor(thinkT * 2) % 3))
    return NAME + ' is consulting the library' + dots
  }
  function setBody(s) {
    if (!bodyText) return
    try {
      const v = String(s || '')
      bodyText.value = v.length > MAX_BUBBLE_CHARS ? v.slice(0, MAX_BUBBLE_CHARS - 1) + '\\u2026' : v
    } catch (e) {}
  }
  function setSuggestions(list) {
    currentSuggestions = (list && list.length ? list : BAKED_SUGGESTIONS).slice(0, 3)
    suggestViews.forEach((b, i) => {
      const q = currentSuggestions[i]
      try {
        b.view.visible = !!q
        if (q) b.text.value = (i + 1) + '.  ' + q
      } catch (e) {}
    })
  }
  function ask(text) {
    if (!text) return
    app.send('moca:guide:ask', { text })
    mode = 'thinking'; thinkT = 0; fullAnswer = ''; shownChars = 0
    setBody(thinkingLine())
  }

  // ---- the speech bubble above the head (this player's private view) --------
  function buildBubble() {
    try {
      const bubble = app.create('ui', {
        space: 'world',
        width: 520,
        height: 380,
        backgroundColor: 'rgba(8, 8, 8, 0.92)',
        borderRadius: 18,
        padding: 18,
        flexDirection: 'column',
        gap: 9,
        billboard: 'y',
        doubleside: true,
      })
      bubble.size = 0.0038
      bubble.position.set(0, 2.6, 0)

      const header = app.create('uitext', {
        value: NAME + ' \\u00b7 \\u201c' + EXHIBITION.name + '\\u201d',
        fontSize: 16,
        color: '#ffffff',
        fontWeight: 'bold',
        lineHeight: 1.2,
      })
      bubble.add(header)

      bodyText = app.create('uitext', {
        value: GREETING,
        fontSize: 13,
        color: '#e6e6e6',
        lineHeight: 1.38,
      })
      bubble.add(bodyText)

      suggestViews = []
      for (let i = 0; i < 3; i++) {
        const view = app.create('uiview', {
          backgroundColor: 'rgba(255, 255, 255, 0.08)',
          borderRadius: 10,
          padding: 9,
        })
        const text = app.create('uitext', { value: ' ', fontSize: 12, color: '#ffffff', lineHeight: 1.25 })
        view.add(text)
        view.cursor = 'pointer'
        ;(function (idx) {
          view.onPointerDown = () => {
            const q = currentSuggestions[idx]
            if (q) ask(q)
          }
          view.onPointerEnter = () => { try { view.backgroundColor = 'rgba(255, 255, 255, 0.16)' } catch (e) {} }
          view.onPointerLeave = () => { try { view.backgroundColor = 'rgba(255, 255, 255, 0.08)' } catch (e) {} }
        })(i)
        bubble.add(view)
        suggestViews.push({ view, text })
      }

      const hint = app.create('uitext', {
        value: 'Hold E or type your question in the chat \\u00b7 a number (1\\u20133) picks a suggestion.',
        fontSize: 10.5,
        color: '#9a9a9a',
        lineHeight: 1.25,
      })
      bubble.add(hint)

      app.add(bubble)
      setSuggestions(currentSuggestions)
    } catch (e) {
      console.error('[moca-guide] bubble failed', e && e.message)
    }
  }
  buildBubble()

  // ---- hold E to engage (nudges the server to start following) --------------
  try {
    const act = app.create('action')
    act.label = 'Talk to ' + NAME
    act.distance = TALK_DIST
    act.duration = 0.3
    act.onTrigger = () => { app.send('moca:guide:open', {}) }
    act.position.set(0, 1.2, 0)
    app.add(act)
  } catch (e) {
    /* action nodes unavailable — chat + suggestions still work */
  }

  app.on('moca:guide:hello', (d) => {
    if (d && Array.isArray(d.suggestions)) setSuggestions(d.suggestions)
  })
  app.on('moca:guide:thinking', () => {
    mode = 'thinking'; thinkT = 0; fullAnswer = ''; shownChars = 0
    setBody(thinkingLine())
  })
  app.on('moca:guide:answer', (d) => {
    if (!d) return
    if (Array.isArray(d.suggestions)) setSuggestions(d.suggestions)
    fullAnswer = String(d.text || '')
    shownChars = 0
    mode = 'talking'
    speakAnswer(d.audioUrl)
  })

  // ---- per-frame: locomotion emote, typewriter reveal, thinking dots, facing
  let sinceCheck = 0
  let greeted = false
  let pX = app.position.x, pY = app.position.y, pZ = app.position.z
  app.on('update', (dt) => {
    const following = moveGuide(dt, followId, HOME)

    // The guide's own per-frame displacement → locomotion emote.
    const mdt = Math.max(dt, 0.001)
    const sdx = app.position.x - pX, sdy = app.position.y - pY, sdz = app.position.z - pZ
    pX = app.position.x; pY = app.position.y; pZ = app.position.z
    const hSpeed = Math.sqrt(sdx * sdx + sdz * sdz) / mdt
    const vSpeed = Math.abs(sdy) / mdt
    let want
    if (hSpeed > 0.18 || vSpeed > 0.35) {
      want = (vSpeed > hSpeed && vSpeed > 0.5) ? EMOTE.float : EMOTE.walk
    } else {
      want = (mode === 'thinking' || mode === 'talking') ? EMOTE.talk : EMOTE.idle
    }
    setEmote(want)

    // Thinking ellipsis, then typewriter-reveal the answer (no in-world SSE —
    // the wrapped fetch can't stream — so we reveal the whole answer here).
    if (mode === 'thinking') {
      thinkT += dt
      setBody(thinkingLine())
    } else if (mode === 'talking') {
      if (shownChars < fullAnswer.length) {
        shownChars = Math.min(fullAnswer.length, shownChars + Math.max(2, Math.ceil(dt * 45)))
        setBody(fullAnswer.slice(0, shownChars))
      } else {
        mode = 'idle'
      }
    }

    sinceCheck += dt
    if (sinceCheck < 0.25) return
    sinceCheck = 0
    let me = null
    try { me = world.getPlayer() } catch (e) {}
    if (!me || !me.position) return
    const dx = me.position.x - app.position.x
    const dz = me.position.z - app.position.z
    const distSq = dx * dx + dz * dz
    if (!greeted && distSq < (TALK_DIST + 4) * (TALK_DIST + 4)) {
      greeted = true
      try {
        world.chat({ from: NAME, body: 'Welcome to \\u201c' + EXHIBITION.name + '\\u201d! Hold E to talk to me, or just type your question.' }, false)
      } catch (e) {}
    }
    // When not following, face whoever is closest (VRM faces local -Z → +PI).
    if (!following && distSq < 49 && distSq > 0.04) {
      try {
        const yaw = Math.atan2(dx, dz) + Math.PI
        app.quaternion.set(0, Math.sin(yaw / 2), 0, Math.cos(yaw / 2))
      } catch (e) {}
    }
  })
}
`;
}
