/**
 * Generates the Hyperfy app script for the MOCA museum guide — a walking,
 * talking VRM avatar that visitors talk to about the exhibition they're in.
 *
 * The blueprint keeps the `.vrm` as its model; the script grabs the engine's
 * avatar node (`app.get('avatar')`) and drives locomotion + gesture emotes as
 * the guide follows the visitor (with gravity). The conversation lives in a
 * beautiful billboarded WORLD-SPACE PANEL above the guide — a live status line
 * (here/thinking/speaking), name, the visitor's last question, the answer, and
 * tappable suggestions — with the full text mirrored to the visitor's private
 * world chat as a transcript. When enabled the guide speaks each answer aloud
 * via an audio node fed by the guide API's TTS — synthesis is pre-warmed
 * server-side at ask time so it runs in parallel while the visitor reads the
 * text and the voice catches up in a few seconds (no cold synth on the GET).
 * After a fast reply the server briefly
 * polls `/v1/guide/followup` and, when a deeper insight lands, the guide
 * proactively offers it as a short spoken aside — closing the loop.
 *
 * Answers are AGENTIC and per-player: the SERVER side of the script calls
 * the MOCA API (`POST /v1/guide/ask`) — which combines the registered
 * exhibition context (rooms, architects, artists, works) with the museum's
 * Cortex Library and an optional Art DeCC0 persona — and replies privately
 * via `app.sendTo`, so two visitors can quiz the guide at once without
 * seeing each other's conversations. Per-player history rides along, so the
 * guide reacts to the conversation, not just the last question.
 *
 * Baked suggestions keep the guide useful (greeting + question starters)
 * even when the museum API is unreachable; live answers then degrade to a
 * polite offline line.
 *
 * KEEP IN SYNC with apps/museum/src/lib/museum/hyperfy/guide-script.ts —
 * the browser twin used by the "Spawn to Hyperfy" dialog.
 */

/** JSON.stringify safe to embed in a generated script. */
function inline(value) {
  return JSON.stringify(value).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

/**
 * @param {object} opts
 * @param {string} opts.exhibitionId   stable exhibition id (registered with the guide API)
 * @param {string} opts.exhibitionName display title, e.g. "Echoes of the Mind"
 * @param {string} [opts.apiUrl]       MOCA API base (default https://api.moca.qwellco.de)
 * @param {string} [opts.guideName]    the guide's display name (default "Oblak")
 * @param {number} [opts.decc0Id]      Art DeCC0 token id whose persona the guide adopts (default 2875, Oblak)
 * @param {string} [opts.customSoul]   a SOUL.md the guide embodies (beats decc0/soulRef)
 * @param {string} [opts.soulName]     display name for the custom soul
 * @param {{chainId:number,address:string,tokenId:string}|null} [opts.soulRef]
 *   a Soulweaver soul coordinate, resolved by the API at answer time
 * @param {string[]} [opts.suggestions] baked question starters (offline fallback)
 * @param {number} [opts.roomCount]
 * @param {number} [opts.artworkCount]
 * @param {string} [opts.avatarUrl]    the .vrm body the script animates (asset/absolute URL)
 * @param {boolean} [opts.speak]       speak answers aloud in-world (default true)
 * @param {string} [opts.voice]        Venice TTS voice id (empty = API default)
 * @returns {string} the app script source
 */
export function generateGuideScript({
  exhibitionId,
  exhibitionName,
  apiUrl = "https://api.moca.qwellco.de",
  guideName = "Oblak",
  decc0Id = 2875,
  customSoul = "",
  soulName = "",
  soulRef = null,
  suggestions = [],
  roomCount = 0,
  artworkCount = 0,
  avatarUrl = "",
  speak = true,
  voice = "",
}) {
  const config = {
    exhibition: { id: exhibitionId, name: exhibitionName, rooms: roomCount, artworks: artworkCount },
    apiUrl: apiUrl.replace(/\/+$/, ""),
    guideName,
    decc0Id: Number(decc0Id) || 0,
    customSoul: String(customSoul || "").slice(0, 4000),
    soulName: String(soulName || "").slice(0, 60),
    soulRef: soulRef && soulRef.chainId && soulRef.address && soulRef.tokenId
      ? { chainId: Number(soulRef.chainId), address: String(soulRef.address), tokenId: String(soulRef.tokenId) }
      : null,
    suggestions: suggestions.slice(0, 6),
    avatarUrl: String(avatarUrl || ""),
    speak: speak !== false,
    voice: String(voice || "").slice(0, 40),
  };

  return `// MOCA museum guide — generated by the Museum of Crypto Art world builder.
// A walking, talking VRM avatar that answers visitor questions about this
// exhibition. It greets you from a panel above its head, follows you once you
// engage, and (when enabled) speaks its answers aloud. Just type your question
// in the chat while near it (or hold E to have it walk with you). Answers are
// private per visitor. Right-click in build mode to change name/persona/API.

app.configure([
  { key: 'guideName', type: 'text', label: 'Guide name', initial: ${inline(config.guideName)} },
  { key: 'decc0', type: 'number', label: 'DeCC0 persona', hint: 'Art DeCC0 token id whose soul the guide adopts (default 2875 = Oblak, the cryptoart guide)', min: 0, max: 10000, step: 1, initial: ${inline(config.decc0Id)} },
  { key: 'customSoul', type: 'textarea', label: 'Custom SOUL', hint: 'Paste a SOUL.md and the guide embodies it (overrides the DeCC0 persona)', initial: ${inline(config.customSoul)} },
  { key: 'apiUrl', type: 'text', label: 'Museum API', hint: 'MOCA API base URL the guide asks for answers', initial: ${inline(config.apiUrl)} },
  { key: 'exhibitionId', type: 'text', label: 'Exhibition id', hint: 'The registered exhibition this guide speaks for (POST /v1/guide/exhibitions)', initial: ${inline(config.exhibition.id)} },
  { key: 'exhibitionName', type: 'text', label: 'Exhibition title', initial: ${inline(config.exhibition.name)} },
  { key: 'avatarUrl', type: 'text', label: 'Avatar (.vrm)', hint: 'The VRM body the guide animates (asset or absolute URL)', initial: ${inline(config.avatarUrl)} },
  { key: 'speak', type: 'toggle', label: 'Speak answers', hint: 'Read answers aloud in-world (Venice TTS via the guide API)', trueLabel: 'On', falseLabel: 'Off', initial: ${inline(config.speak)} },
  { key: 'voice', type: 'text', label: 'Voice', hint: 'Venice TTS voice id (empty = default). e.g. Serena, Vivian, Dylan', initial: ${inline(config.voice)} },
  { key: 'talkDistance', type: 'range', label: 'Talk distance', hint: 'How close visitors must be to start talking (meters)', min: 1, max: 8, step: 0.5, initial: 3 },
  { key: 'chatRange', type: 'range', label: 'Chat range', hint: 'How far the guide hears typed chat questions (meters)', min: 4, max: 30, step: 1, initial: 10 },
])

const BAKED = ${inline(config.exhibition)}
const BAKED_SUGGESTIONS = ${inline(config.suggestions)}

const str = (v, d) => (typeof v === 'string' && v.trim() ? v.trim() : d)
const numOr = (v, d) => (typeof v === 'number' && v === v ? v : d)
// Retargetable: point a dropped guide at any registered exhibition by id.
const EXHIBITION = {
  id: str(props.exhibitionId, BAKED.id),
  name: str(props.exhibitionName, BAKED.name),
  rooms: BAKED.rooms,
  artworks: BAKED.artworks,
}
const NAME = str(props.guideName, ${inline(config.guideName)})
const DECC0 = numOr(props.decc0, ${inline(config.decc0Id)})
const CUSTOM_SOUL = str(props.customSoul, ${inline(config.customSoul)})
const SOUL_NAME = ${inline(config.soulName)}
const SOUL_REF = ${inline(config.soulRef)}
const API = str(props.apiUrl, ${inline(config.apiUrl)}).replace(/\\/+$/, '')
const AVATAR_URL = str(props.avatarUrl, ${inline(config.avatarUrl)})
const SPEAK = props.speak !== false
const VOICE = str(props.voice, ${inline(config.voice)})
const TALK_DIST = numOr(props.talkDistance, 3)
const CHAT_RANGE = numOr(props.chatRange, 10)

const GREETING = 'Welcome to \\u201c' + EXHIBITION.name + '\\u201d! I\\u2019m ' + NAME + ', your guide' +
  (EXHIBITION.artworks ? ' \\u2014 ' + EXHIBITION.rooms + ' room(s), ' + EXHIBITION.artworks + ' works to discover' : '') +
  '. Ask me anything about the works, artists or rooms \\u2014 just type in the chat while you\\u2019re near me.'
const OFFLINE = 'My deeper knowledge is offline right now \\u2014 walk the rooms and come back to me in a little while.'

// Follow behaviour: after a visitor interacts (hold E or asks a question) the
// guide trails them. Hyperfy doesn't network script-driven transforms, so BOTH
// the server and every client run this SAME math against the followed player's
// (networked, so shared) position — the server so its proximity/chat-range
// checks track the visitor it's walking with, the clients for the visual. No
// transform replication needed; they agree because the input is the same.
const FOLLOW_STANDOFF = 1.8
const FOLLOW_LERP = 2.6
const GRAVITY = 24 // m/s² — the curator falls like a player, never hovers
let guideVy = 0
function moveGuide(dt, followId, home) {
  const A = app.position
  let target = null
  if (followId) { try { target = world.getPlayer(followId) } catch (e) {} }

  // Resolve where the curator wants to be: a standoff behind the followed
  // player, or its home post. tx/tz horizontal, ty the level to settle at.
  let tx = A.x, tz = A.z, ty = A.y
  const following = !!(target && target.position)
  if (following) {
    const dx = target.position.x - A.x
    const dz = target.position.z - A.z
    const dist = Math.sqrt(dx * dx + dz * dz) || 0.0001
    if (dist > FOLLOW_STANDOFF) {
      tx = target.position.x - (dx / dist) * FOLLOW_STANDOFF
      tz = target.position.z - (dz / dist) * FOLLOW_STANDOFF
    }
    ty = target.position.y
  } else if (home) {
    tx = home.x; tz = home.z; ty = home.y
  } else {
    return false
  }

  // Horizontal: smooth follow.
  const k = Math.min(1, FOLLOW_LERP * dt)
  const nx = A.x + (tx - A.x) * k
  const nz = A.z + (tz - A.z) * k

  // Vertical: gravity. When the target/ground is BELOW, fall (accelerating)
  // instead of slow-lerping — so the curator drops to the floor with you and
  // doesn't keep walking in mid-air. When above (you flew up), rise smoothly.
  let ny
  if (A.y > ty + 0.03) {
    guideVy = Math.max(guideVy - GRAVITY * dt, -40)
    ny = A.y + guideVy * dt
    if (ny <= ty) { ny = ty; guideVy = 0 }
  } else {
    guideVy = 0
    ny = A.y + (ty - A.y) * k
  }
  app.position.set(nx, ny, nz)

  if (following) {
    const yaw = Math.atan2(target.position.x - app.position.x, target.position.z - app.position.z) + Math.PI
    app.quaternion.set(0, Math.sin(yaw / 2), 0, Math.cos(yaw / 2))
  }
  return following
}

// ---------------------------------------------------------------- server ----
if (world.isServer) {
  // Whoever last interacts becomes the follow target (broadcast to clients via
  // app.send; mirrored to app.state.follow so late-joiners pick it up).
  const HOME = { x: app.position.x, y: app.position.y, z: app.position.z }
  let followId = null
  function setFollow(id) {
    if (id == null || followId === id) return
    followId = id
    try { app.state.follow = id } catch (e) {}
    app.send('moca:guide:follow', { id })
  }
  function clearFollow(id) {
    if (id != null && followId !== id) return
    followId = null
    try { app.state.follow = null } catch (e) {}
    app.send('moca:guide:follow', { id: null })
  }
  // playerId -> { open, history, suggestions, busy, lastAsk, sid }
  // sid is a stable per-visitor id sent to the guide API so it can hold this
  // visitor's session memory + Cortex-mined insights server-side (hybrid path).
  const sessions = {}
  const session = (playerId) => {
    if (!sessions[playerId]) {
      const sid = ('p' + String(playerId)).replace(/[^\\w-]/g, '').slice(0, 48) || ('p' + Date.now())
      sessions[playerId] = { open: false, history: [], suggestions: BAKED_SUGGESTIONS, busy: false, lastAsk: 0, sid, pollUntil: 0, polling: false }
    }
    return sessions[playerId]
  }

  // Close the loop: after a fast reply, the API may mine a deeper insight and
  // compose a short proactive aside. Poll for it briefly and, when it lands,
  // push it privately to the visitor — so the conversation gets richer on its
  // own, not just on the next question.
  async function pollFollowup(playerId, s) {
    if (s.polling) return
    s.polling = true
    try {
      const url = API + '/v1/guide/followup?exhibition=' + encodeURIComponent(EXHIBITION.id) + '&session=' + encodeURIComponent(s.sid)
      const res = await fetch(url)
      if (res && res.ok) {
        const body = await res.json()
        const d = body && body.data
        if (d && d.text) {
          s.pollUntil = 0 // one aside per turn is enough
          s.history.push({ role: 'assistant', content: String(d.text).slice(0, 2000) })
          if (s.history.length > 16) s.history.splice(0, s.history.length - 16)
          app.sendTo(playerId, 'moca:guide:followup', {
            text: String(d.text),
            audioUrl: typeof d.audioUrl === 'string' ? d.audioUrl : null,
            persona: NAME,
            suggestions: s.suggestions,
          })
        }
      }
    } catch (e) {
      /* the aside is a bonus — never let it disturb the world */
    } finally {
      s.polling = false
    }
  }

  function nearGuide(playerId, range) {
    try {
      const p = world.getPlayer(playerId)
      if (!p || !p.position) return false
      const dx = p.position.x - app.position.x
      const dy = p.position.y - app.position.y
      const dz = p.position.z - app.position.z
      return dx * dx + dy * dy + dz * dz <= range * range
    } catch (e) {
      return false
    }
  }

  async function handleAsk(playerId, text, viaChat) {
    const s = session(playerId)
    const now = Date.now()
    if (s.busy || now - s.lastAsk < 1500) return
    // "1"/"2"/"3" picks one of the suggestions last shown to this player.
    const question = text
    if (!question || question.length < 2) return
    setFollow(playerId)
    s.busy = true
    s.lastAsk = now
    app.sendTo(playerId, 'moca:guide:thinking', { question })
    let answer = OFFLINE
    let persona = NAME
    let sources = []
    let audioUrl = null
    let mode = null
    try {
      const player = world.getPlayer(playerId)
      const res = await fetch(API + '/v1/guide/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          exhibition: EXHIBITION.id,
          session: s.sid,
          question: question.slice(0, 2000),
          history: s.history.slice(-8),
          decc0: DECC0 || undefined,
          soul: CUSTOM_SOUL || undefined,
          soulName: (CUSTOM_SOUL && SOUL_NAME) || undefined,
          soulRef: SOUL_REF || undefined,
          speak: SPEAK,
          voice: VOICE || undefined,
          visitor: player && player.name ? String(player.name).slice(0, 48) : undefined,
          // Spatial awareness: where the visitor (whom the guide follows) and the
          // guide are standing, in world meters — the API maps these to the room
          // they're in to situate (and narrow) the answer.
          visitorPos: player && player.position ? { x: player.position.x, z: player.position.z } : undefined,
          guidePos: { x: app.position.x, z: app.position.z },
        }),
      })
      if (res && res.ok) {
        const body = await res.json()
        const d = body && body.data
        if (d && d.answer) {
          answer = String(d.answer)
          persona = str(d.persona, NAME)
          if (Array.isArray(d.suggestions) && d.suggestions.length) s.suggestions = d.suggestions
          if (Array.isArray(d.sources)) sources = d.sources
          if (typeof d.audioUrl === 'string') audioUrl = d.audioUrl
          if (typeof d.mode === 'string') mode = d.mode
        }
      }
    } catch (e) {
      console.error('[moca-guide] ask failed', e && e.message)
    }
    s.history.push({ role: 'user', content: question })
    s.history.push({ role: 'assistant', content: answer.slice(0, 2000) })
    if (s.history.length > 16) s.history.splice(0, s.history.length - 16)
    s.busy = false
    // Only the hybrid fast path mines a follow-up; open a poll window wide enough
    // to cover a deep Cortex mine + the aside compose (~30s observed) plus margin.
    s.pollUntil = mode === 'fast' ? Date.now() + 50000 : 0
    app.sendTo(playerId, 'moca:guide:answer', {
      question,
      text: answer,
      persona,
      sources,
      audioUrl,
      suggestions: s.suggestions,
      viaChat: !!viaChat,
    })
  }

  app.on('moca:guide:open', (d, playerId) => {
    const s = session(playerId)
    s.open = true
    setFollow(playerId)
    app.sendTo(playerId, 'moca:guide:hello', { suggestions: s.suggestions })
  })
  app.on('moca:guide:close', (d, playerId) => {
    session(playerId).open = false
  })
  app.on('moca:guide:unfollow', (d, playerId) => {
    clearFollow(playerId)
    session(playerId).open = false
  })
  app.on('moca:guide:ask', (d, playerId) => {
    if (!d || typeof d.text !== 'string') return
    if (!nearGuide(playerId, Math.max(CHAT_RANGE, TALK_DIST + 2))) return
    handleAsk(playerId, d.text.trim(), false)
  })

  // Free text: any chat from a visitor standing near the guide is a question
  // — no panel needed, exactly what the greeting promises. Typing "1"-"3"
  // picks an offered question. "/ask <question>" also works.
  world.on('chat', (msg) => {
    try {
      if (!msg || !msg.fromId || typeof msg.body !== 'string') return
      if (msg.body.startsWith('/')) return
      if (!nearGuide(msg.fromId, CHAT_RANGE)) return
      handleAsk(msg.fromId, msg.body.trim(), true)
    } catch (e) {
      console.error('[moca-guide] chat failed', e && e.message)
    }
  })
  world.on('command', (d) => {
    try {
      if (!d || !d.playerId || !Array.isArray(d.args)) return
      if (String(d.args[0]).toLowerCase() !== 'ask') return
      const text = d.args.slice(1).join(' ').trim()
      if (!text) return
      if (!nearGuide(d.playerId, CHAT_RANGE)) return
      handleAsk(d.playerId, text, true)
    } catch (e) {
      /* commands are best-effort */
    }
  })
  world.on('leave', (e) => {
    if (e && e.playerId) {
      delete sessions[e.playerId]
      clearFollow(e.playerId)
    }
  })
  // Server-authoritative motion so chat-range/proximity track the followed
  // visitor (clients run the identical math for the visual). Eases back to its
  // post when no one's being followed.
  let pollT = 0
  app.on('fixedUpdate', (dt) => {
    try { moveGuide(dt, followId, HOME) } catch (e) {}
    // Poll for proactive follow-ups roughly every 5s for any visitor in their
    // post-reply window — cheap, and stops the moment an aside is delivered.
    pollT += dt
    if (pollT < 5) return
    pollT = 0
    const now = Date.now()
    for (const pid in sessions) {
      const s = sessions[pid]
      if (s && !s.busy && s.pollUntil && now <= s.pollUntil) pollFollowup(pid, s)
    }
  })
}

// ---------------------------------------------------------------- client ----
if (world.isClient) {
  // The guide's resting post + who it's currently following (server tells us).
  const HOME = { x: app.position.x, y: app.position.y, z: app.position.z }
  let followId = (app.state && app.state.follow) || null
  let myId = null
  let actionNode = null
  function followingMe() { return followId != null && myId != null && followId === myId }
  function actionLabel() { return followingMe() ? 'Walk on your own' : 'Walk with ' + NAME }
  function refreshActionLabel() { if (actionNode) { try { actionNode.label = actionLabel() } catch (e) {} } }
  app.on('moca:guide:follow', (d) => { followId = d && d.id != null ? d.id : null; refreshActionLabel() })

  // ---- the body: the blueprint .vrm renders as an 'avatar' node ------------
  // Hyperfy loads a .vrm model as a group whose child is an avatar node with
  // id 'avatar' (App.build → glb.toNodes()). We grab that node and drive the
  // engine's built-in emote clips for locomotion + gesture. (Setting the
  // blueprint model to null instead would crash App.build — it assumes a model.)
  const EMOTE = {
    idle: 'asset://mp-idle.glb',
    walk: 'asset://mp-walk.glb?s=1.5',
    talk: 'asset://emote-talk.glb',
    float: 'asset://emote-float.glb',
    fall: 'asset://emote-fall.glb',
  }
  let body = null
  function avatarNode() {
    if (!body) { try { body = app.get('avatar') } catch (e) {} }
    return body
  }
  let curEmote = null
  function setEmote(url) {
    const b = avatarNode()
    if (!b || url === curEmote) return
    curEmote = url
    try { b.emote = url } catch (e) {}
  }
  setEmote(EMOTE.idle)

  try {
    const tag = app.create('nametag', { label: NAME })
    tag.position.set(0, 2.15, 0)
    app.add(tag)
  } catch (e) {
    /* nametags unavailable — the panel still names the guide */
  }

  // ---- a beautiful world-space conversation panel --------------------------
  // The whole exchange lives in a billboarded panel above the guide: status
  // line, name, the visitor's last question, the guide's answer, suggested
  // questions, and a how-to hint. We build it ONCE and only swap text values
  // (rebuilding nodes per turn is expensive and flickers). Full answers are
  // also mirrored to this client's private world chat as a transcript.
  const C = {
    bg: 'rgba(11, 11, 14, 0.93)',
    name: '#ffffff',
    muted: '#9aa0a6',
    body: '#ededf2',
    ready: '#c9a227',  // MOCA gold — resting
    think: '#e6b53d',  // amber — consulting
    speak: '#7bdcb5',  // teal — speaking
    note: '#c9a227',   // the proactive aside
    sugg: '#aeb4bd',
    hint: '#6f747b',
  }
  let panel = null, statusNode = null, titleNode = null, qNode = null, aNode = null
  let panelState = 'idle' // idle | thinking | speaking
  let thinkT = 0
  let clock = 0           // seconds, accumulated from update(dt)
  let speakingUntil = 0   // clock time the "speaking" indicator should hold until

  function clip(s, n) { s = String(s || ''); return s.length > n ? s.slice(0, n - 1) + '\\u2026' : s }
  function setVal(node, v) { if (node) { try { node.value = v } catch (e) {} } }
  function setColor(node, c) { if (node) { try { node.color = c } catch (e) {} } }

  function renderStatus() {
    if (panelState === 'thinking') {
      const dots = '.'.repeat(1 + (Math.floor(thinkT * 2) % 3))
      setVal(statusNode, '\\u25cf  ' + NAME + ' is thinking' + dots)
      setColor(statusNode, C.think)
    } else if (panelState === 'speaking') {
      setVal(statusNode, '\\u25cf  speaking\\u2026')
      setColor(statusNode, C.speak)
    } else {
      setVal(statusNode, '\\u25cf  here to guide you')
      setColor(statusNode, C.ready)
    }
  }
  function buildPanel() {
    try {
      panel = app.create('ui', {
        space: 'world', width: 580, height: 392,
        backgroundColor: C.bg, borderRadius: 22, padding: 28,
        flexDirection: 'column', justifyContent: 'flex-start', gap: 9,
        billboard: 'y', doubleside: true, pointerEvents: false,
      })
      panel.size = 0.004
      panel.position.set(0, 2.85, 0)
      statusNode = app.create('uitext', { value: '', fontSize: 13, color: C.ready, lineHeight: 1.2 })
      titleNode = app.create('uitext', { value: NAME + '  \\u00b7  your guide', fontSize: 21, color: C.name, fontWeight: 'bold', lineHeight: 1.2 })
      qNode = app.create('uitext', { value: '', fontSize: 14, color: C.muted, lineHeight: 1.35 })
      aNode = app.create('uitext', { value: GREETING, fontSize: 16, color: C.body, lineHeight: 1.5 })
      const hint = app.create('uitext', { value: '\\u2328 just type your question, or hold E to walk with me', fontSize: 12, color: C.hint, lineHeight: 1.3 })
      panel.add(statusNode); panel.add(titleNode); panel.add(qNode); panel.add(aNode); panel.add(hint)
      app.add(panel)
      renderStatus()
    } catch (e) {
      console.error('[moca-guide] panel failed', e && e.message)
    }
  }
  buildPanel()

  // ---- voice: an audio node that plays each synthesized answer --------------
  let audio = null
  function speakAnswer(url, text) {
    if (!SPEAK || !url) return
    try {
      if (audio) {
        try { audio.stop() } catch (e) {}
        try { app.remove(audio) } catch (e) {}
        audio = null
      }
      audio = app.create('audio', { src: url, spatial: true, volume: 1, loop: false })
      app.add(audio)
      audio.play()
      // Hold the "speaking" state for a rough estimate of the clip length so the
      // indicator + talk emote track the voice (no end-event in the sandbox).
      const secs = Math.min(15, Math.max(3, Math.round(String(text || '').length * 0.055)))
      speakingUntil = clock + secs
      panelState = 'speaking'; renderStatus()
    } catch (e) {
      console.error('[moca-guide] audio failed', e && e.message)
    }
  }
  function resolveAudio(u) {
    return typeof u === 'string' && u ? (u.charAt(0) === '/' ? API + u : u) : null
  }
  // Private transcript: mirror the spoken text into THIS client's chat only
  // (false = local) so visitors can scroll back through the conversation.
  function mirrorChat(text, from) {
    const chunks = String(text || '').match(/[\\s\\S]{1,300}/g) || []
    chunks.slice(0, 6).forEach((c) => { try { world.chat({ from: from || NAME, body: c }, false) } catch (e) {} })
  }

  app.on('moca:guide:thinking', (d) => {
    panelState = 'thinking'; thinkT = 0; speakingUntil = 0
    setVal(qNode, d && d.question ? 'you asked: \\u201c' + clip(d.question, 120) + '\\u201d' : '')
    setVal(aNode, '')
    renderStatus()
  })
  app.on('moca:guide:answer', (d) => {
    if (!d) return
    setVal(qNode, d.question ? 'you asked: \\u201c' + clip(d.question, 120) + '\\u201d' : '')
    setVal(aNode, clip(d.text, 380))
    mirrorChat(d.text, str(d.persona, NAME))
    const au = resolveAudio(d.audioUrl)
    if (au) speakAnswer(au, d.text)
    else { panelState = 'idle'; renderStatus() }
  })
  // The proactive aside: a deeper detail the guide dug up after answering.
  app.on('moca:guide:followup', (d) => {
    if (!d || !d.text) return
    setVal(aNode, '\\u2726  ' + clip(d.text, 360))
    setColor(aNode, C.body)
    mirrorChat('\\u2726 ' + d.text, str(d.persona, NAME))
    const au = resolveAudio(d.audioUrl)
    if (au) speakAnswer(au, d.text)
  })

  // ---- hold E to engage (nudges the server to start following) --------------
  try {
    const act = app.create('action')
    actionNode = act
    act.label = actionLabel()
    act.distance = TALK_DIST
    act.duration = 0.3
    act.onTrigger = () => {
      if (followingMe()) {
        app.send('moca:guide:unfollow', {})
      } else {
        app.send('moca:guide:open', {})
      }
    }
    // At the curator's feet (not eye level) so the prompt never blocks his face
    // — or avatars standing behind the player.
    act.position.set(0, 0.1, 0)
    app.add(act)
  } catch (e) {
    /* action nodes unavailable — chat still works */
  }

  // ---- per-frame: locomotion emote, live indicator, facing -----------------
  let sinceCheck = 0
  let pX = app.position.x, pY = app.position.y, pZ = app.position.z
  // Followed player's previous position — used to mirror their vertical state.
  let fpX = 0, fpY = 0, fpZ = 0, haveFp = false
  app.on('update', (dt) => {
    clock += dt
    const following = moveGuide(dt, followId, HOME)

    // Drop out of "speaking" once the estimated clip has played.
    if (panelState === 'speaking' && clock >= speakingUntil) { panelState = 'idle'; renderStatus() }
    // Animate the thinking dots while a question is in flight.
    if (panelState === 'thinking') { thinkT += dt; renderStatus() }

    // Locomotion emote: mirror the FOLLOWED player's motion so the curator
    // flies when they fly up, falls when they drop, and walks on the ground.
    // (The player proxy has no velocity/grounded flag, so derive it from their
    // per-frame position; HOME.y is the curator's ground post = ground ref.)
    const mdt = Math.max(dt, 0.001)
    let want = (panelState === 'thinking' || panelState === 'speaking') ? EMOTE.talk : EMOTE.idle
    let fp = null
    if (followId) { try { fp = world.getPlayer(followId) } catch (e) {} }
    if (fp && fp.position) {
      if (haveFp) {
        const fvy = (fp.position.y - fpY) / mdt
        const fdx = fp.position.x - fpX, fdz = fp.position.z - fpZ
        const fhs = Math.sqrt(fdx * fdx + fdz * fdz) / mdt
        const air = fp.position.y - HOME.y // height above the ground post
        if (air > 1.5) want = fvy < -1.2 ? EMOTE.fall : EMOTE.float // airborne: dropping → fall, else fly/hover
        else if (fvy < -1.2) want = EMOTE.fall // dropping near the ground
        else if (fhs > 0.2) want = EMOTE.walk // walking
      }
      fpX = fp.position.x; fpY = fp.position.y; fpZ = fp.position.z; haveFp = true
    } else {
      haveFp = false
      // Not following — animate the curator's own motion (e.g. easing home).
      const sdx = app.position.x - pX, sdz = app.position.z - pZ
      if (Math.sqrt(sdx * sdx + sdz * sdz) / mdt > 0.18) want = EMOTE.walk
    }
    pX = app.position.x; pY = app.position.y; pZ = app.position.z
    setEmote(want)

    sinceCheck += dt
    if (sinceCheck < 0.25) return
    sinceCheck = 0
    let me = null
    try { me = world.getPlayer() } catch (e) {}
    if (me && myId == null && me.id != null) { myId = me.id; refreshActionLabel() }
    if (!me || !me.position) return
    const dx = me.position.x - app.position.x
    const dz = me.position.z - app.position.z
    const distSq = dx * dx + dz * dz
    // When not following, face whoever is closest (VRM faces local -Z → +PI).
    if (!following && distSq < 49 && distSq > 0.04) {
      try {
        const yaw = Math.atan2(dx, dz) + Math.PI
        app.quaternion.set(0, Math.sin(yaw / 2), 0, Math.cos(yaw / 2))
      } catch (e) {}
    }
  })
}
`;
}
